Repository AY2021S1-CS2103T-F12-3/tp, pull requests merged in 2020-09, with the labels that each got.

#48 Add NFRs under privacy, Quality and Tech
  docs/DeveloperGuideCAP5.md
Labels: priority.High, type.documentation

#46 Add add module feature in the UG
  docs/UserGuide.md
Labels: priority.High, type.documentation

#54 Update Readme: Added Photo
  README.md
  docs/images/Ui.png
Labels: type.Task

#63 Change image file from David.png to davidcaiqifan.png
  docs/AboutUs.md
  docs/images/davidcaiqifan.png
Labels: priority.High, type.documentation

#67 Add schedule use case
  docs/DeveloperGuide.md
Labels: priority.High, type.documentation

#76 Rename Setting up markdown file to correct file name
  docs/DeveloperGuide.md
  docs/SettingUp.md
Labels: priority.High, type.documentation

#70 Base setup for UI and parser
  build.gradle
  src/main/java/tp/cap5buddy/cap5buddy.java
  src/main/java/tp/cap5buddy/parser/Parser.java
  src/main/java/tp/cap5buddy/parser/ParserManager.java
  src/main/java/tp/cap5buddy/parser/Tokenizer.java
  src/main/java/tp/cap5buddy/ui/Messages.java
  src/main/java/tp/cap5buddy/ui/Ui.java
Labels: priority.High, severity.High, type.code

#82 V1.2 code quality
  src/main/java/tp/cap5buddy/modules/ModuleList.java
  src/main/java/tp/cap5buddy/parser/AddModuleParser.java
  src/main/java/tp/cap5buddy/parser/AddZoomLinkParser.java
  src/main/java/tp/cap5buddy/parser/ParserManager.java
  src/main/java/tp/cap5buddy/ui/Ui.java
Labels: priority.High, severity.High, type.code

#84 Shift logic handling into LogicManager
  src/main/java/tp/cap5buddy/Cap5buddy.java
  src/main/java/tp/cap5buddy/logic/Logic.java
  src/main/java/tp/cap5buddy/logic/LogicManager.java
  src/main/java/tp/cap5buddy/logic/commands/AddModuleCommand.java
  src/main/java/tp/cap5buddy/logic/commands/AddZoomLinkCommand.java
  src/main/java/tp/cap5buddy/logic/commands/Command.java
  src/main/java/tp/cap5buddy/logic/commands/ResultCommand.java
  src/main/java/tp/cap5buddy/logic/parser/AddModuleParser.java
  src/main/java/tp/cap5buddy/logic/parser/AddZoomLinkParser.java
  src/main/java/tp/cap5buddy/logic/parser/Parser.java
  src/main/java/tp/cap5buddy/logic/parser/ParserManager.java
  src/main/java/tp/cap5buddy/logic/parser/Prefix.java
  src/main/java/tp/cap5buddy/logic/parser/PrefixList.java
  src/main/java/tp/cap5buddy/logic/parser/Tokenizer.java
  src/main/java/tp/cap5buddy/logic/parser/exception/ParseException.java
  src/main/java/tp/cap5buddy/ui/Ui.java
Labels: priority.High, severity.High, type.Task, type.code

#87 Add Class UML version 1
  docs/images/Cap5BuddyUML.png
  docs/images/matthiaslhk.jpg
Labels: priority.High, type.documentation
