Repository AY2021S1-CS2103T-F12-3/tp, pull requests merged in 2020-11, with the labels that each got.

#539 Bug : Fix "importantcontact" command not marking contact as important
  src/main/java/seedu/address/model/contact/Contact.java
Labels: priority.High, severity.High, type.Bug, type.code

#553 Implement DeleteZoomLinkCommand
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/contactlistcommands/DeleteContactCommand.java
  src/main/java/seedu/address/logic/commands/contactlistcommands/EditContactCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/AddZoomLinkCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/DeleteZoomLinkCommand.java
  src/main/java/seedu/address/logic/parser/ModuleListParser.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/AddContactParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/AddZoomLinkParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/DeleteZoomLinkParser.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/ModuleLesson.java
  src/main/java/seedu/address/model/module/ZoomLink.java
Labels: priority.Medium, type.Task, type.code

#562 Disable codecov
  .github/workflows/gradle.yml
Labels: priority.High

#555 Implement EditZoomLinkCommand
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/modulelistcommands/EditZoomDescriptor.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/EditZoomLinkCommand.java
  src/main/java/seedu/address/logic/parser/ModuleListParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/EditZoomLinkParser.java
  src/main/java/seedu/address/model/module/Module.java
Labels: priority.Medium, type.Task, type.code

#292 Create Junit tests for classes in Contact package
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/FindModuleCommandParser.java
  src/main/java/seedu/address/model/contact/Contact.java
  src/main/java/seedu/address/model/contact/FindContactCriteria.java
  src/main/java/seedu/address/model/contact/Telegram.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/task/FindTaskCriteria.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/contact/AddressTest.java
  src/test/java/seedu/address/model/contact/ContactContainsTagsPredicateTest.java
  src/test/java/seedu/address/model/contact/ContactNameTest.java
  src/test/java/seedu/address/model/contact/ContactTest.java
  src/test/java/seedu/address/model/contact/EmailTest.java
  src/test/java/seedu/address/model/contact/FindContactCriteriaTest.java
  src/test/java/seedu/address/model/contact/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/contact/PhoneTest.java
  src/test/java/seedu/address/model/contact/TelegramTest.java
  src/test/java/seedu/address/model/contact/UniqueContactListTest.java
  src/test/java/seedu/address/model/contact/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.code

#549 Tests : Update Junit tests for module list commands
  src/main/java/seedu/address/logic/commands/modulelistcommands/EditModuleCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/EditModuleDescriptor.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/AddModuleParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/ModuleNameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/EditModuleDescriptorTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/modulelistcommands/EditModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/modulelistcommands/EditModuleDescriptorTest.java
  src/test/java/seedu/address/logic/commands/modulelistcommands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/modulelistcommands/FindModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/modulelistcommands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/modulelistcommands/ListModuleCommandTest.java
  src/test/java/seedu/address/logic/parser/EditModuleParserTest.java
  src/test/java/seedu/address/testutil/EditModuleDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ModuleBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalModules.java
Labels: priority.High, type.Task, type.code

#545 V1.4 find scheduler
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/schedulercommands/FindEventCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/schedulerparsers/FindEventParser.java
  src/main/java/seedu/address/model/event/EventContainsDatePredicate.java
  src/main/java/seedu/address/model/event/EventContainsTagsPredicate.java
  src/main/java/seedu/address/model/event/EventNameContainsKeyWordsPredicate.java
  src/main/java/seedu/address/model/event/FindEventCriteria.java
Labels: priority.High, type.code

#569 Update GUI : Shows zoom links skeleton
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ViewCommandResult.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/ViewModuleCommand.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/ui/DetailDisplay.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ZoomLinkCard.java
  src/main/java/seedu/address/ui/ZoomLinkPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DetailsDisplay.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ZoomLinkCard.fxml
  src/main/resources/view/ZoomLinkPanel.fxml
Labels: priority.High, type.code

#572 V1.4 GUI Calender
  src/main/java/seedu/address/ui/Calender.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/Calender.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, severity.High, type.code

#564 Scheduler : Integrate undo/redo feature with scheduler commands
  src/main/java/seedu/address/logic/commands/schedulercommands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/schedulercommands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/schedulercommands/EditEventCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedEventList.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java
Labels: priority.High, type.Task, type.code

#295 Create Junit tests for classes and methods in the model package
  src/main/java/seedu/address/model/ContactList.java
  src/main/java/seedu/address/model/contact/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/module/ModuleLesson.java
  src/main/java/seedu/address/model/module/ModuleName.java
  src/main/java/seedu/address/model/module/ZoomLink.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/modulelistcommands/EditModuleCommandTest.java
  src/test/java/seedu/address/model/ContactListTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/ModuleListTest.java
  src/test/java/seedu/address/model/contact/ContactNameTest.java
  src/test/java/seedu/address/model/contact/ContactTest.java
  src/test/java/seedu/address/model/contact/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/contact/UniqueContactListTest.java
  src/test/java/seedu/address/model/module/ModuleLessonTest.java
  src/test/java/seedu/address/model/module/ModuleNameTest.java
  src/test/java/seedu/address/model/module/ModuleTest.java
  src/test/java/seedu/address/model/module/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/module/UniqueModuleListTest.java
  src/test/java/seedu/address/model/module/ZoomLinkTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedModuleTest.java
  src/test/java/seedu/address/storage/JsonModuleListStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/ContactListBuilder.java
  src/test/java/seedu/address/testutil/ModuleBuilder.java
  src/test/java/seedu/address/testutil/TypicalContacts.java
  src/test/java/seedu/address/testutil/TypicalModules.java
Labels: priority.High, type.Task, type.code

#571 Implement Junit tests for Command related classes
  src/main/java/seedu/address/logic/commands/contactlistcommands/HelpContactCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/AddZoomLinkCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/EditZoomDescriptor.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/EditZoomLinkCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/ZoomDescriptor.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/ContactListParser.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/FindContactParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/AddZoomLinkParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/EditZoomLinkParser.java
  src/main/java/seedu/address/logic/parser/todolistparsers/FindTaskParser.java
  src/main/java/seedu/address/model/contact/ContactNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/task/TaskNameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/contactlistcommands/AddContactCommandTest.java
  src/test/java/seedu/address/logic/commands/contactlistcommands/ClearContactCommandTest.java
  src/test/java/seedu/address/logic/commands/contactlistcommands/DeleteContactCommandTest.java
  src/test/java/seedu/address/logic/commands/contactlistcommands/EditContactCommandTest.java
  src/test/java/seedu/address/logic/commands/contactlistcommands/EditContactDescriptorTest.java
  src/test/java/seedu/address/logic/commands/contactlistcommands/FindContactCommandTest.java
  src/test/java/seedu/address/logic/commands/contactlistcommands/ListContactCommandTest.java
  src/test/java/seedu/address/logic/commands/modulelistcommands/AddZoomLinkCommandTest.java
  src/test/java/seedu/address/logic/commands/modulelistcommands/DeleteZoomLinkCommandTest.java
  src/test/java/seedu/address/logic/commands/modulelistcommands/EditZoomLinkCommandTest.java
  src/test/java/seedu/address/logic/commands/modulelistcommands/ZoomDescriptorTest.java
  src/test/java/seedu/address/logic/commands/todolistcommands/FindTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteModuleParserTest.java
  src/test/java/seedu/address/logic/parser/ModuleListParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/contact/ContactNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/module/UniqueModuleListTest.java
  src/test/java/seedu/address/storage/JsonModuleListStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/EditContactDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/FindContactCriteriaBuilder.java
  src/test/java/seedu/address/testutil/FindTaskCriteriaBuilder.java
  src/test/java/seedu/address/testutil/TypicalContacts.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalModules.java
  src/test/java/seedu/address/testutil/ZoomDescriptorBuilder.java
Labels: priority.High, type.Task, type.code

#578 Bug : Fix capcalculator commands not working
  src/main/java/seedu/address/logic/commands/modulelistcommands/CalculateCapCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/TargetCapCalculatorCommand.java
Labels: priority.High, severity.High, type.Bug

#558 Test : Add testutil classes for TodoList
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/testutil/todolist/EditTaskDescriptorBuilder.java
  src/test/java/seedu/address/testutil/todolist/TaskBuilder.java
  src/test/java/seedu/address/testutil/todolist/TodoListBuilder.java
  src/test/java/seedu/address/testutil/todolist/TypicalTasks.java
Labels: priority.High, type.Task, type.code

#433 GUI : Refine and Finalize GUI for TodoList
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/task/Priority.java
  src/main/java/seedu/address/model/task/Status.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TodoListUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/TodoListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DefaultPieChart.css
  src/main/resources/view/TodoListCard.fxml
  src/main/resources/view/TodoListPanel.fxml
Labels: priority.Medium, type.Enhancement, type.code

#574 V1.4 scheduler tests
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/ParserManager.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/ViewModuleCommand.java
  src/main/java/seedu/address/logic/commands/schedulercommands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/schedulercommands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/schedulercommands/EditEventCommand.java
  src/main/java/seedu/address/logic/commands/schedulercommands/FindEventCommand.java
  src/main/java/seedu/address/logic/commands/schedulercommands/ViewEventCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventContainsDatePredicate.java
  src/main/java/seedu/address/model/event/EventContainsTagsPredicate.java
  src/main/java/seedu/address/model/event/EventName.java
  src/main/java/seedu/address/model/event/EventNameContainsKeyWordsPredicate.java
  src/main/java/seedu/address/model/event/EventTime.java
  src/main/java/seedu/address/model/event/FindEventCriteria.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/JsonSerializableEventList.java
  src/test/data/Event/JsonEventListStorageTest/invalidAndValidEventList.json
  src/test/data/Event/JsonEventListStorageTest/invalidEventList.json
  src/test/data/Event/JsonEventListStorageTest/notJsonFormatEventList.json
  src/test/data/Event/JsonSerializableEventListTest/duplicateEventList.json
  src/test/data/Event/JsonSerializableEventListTest/invalidEventList.json
  src/test/data/Event/JsonSerializableEventListTest/typicalEventList.json
  src/test/data/Module/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/Module/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/Module/JsonAddressBookStorageTest/notJsonFormatAddressBook.json
  src/test/data/Module/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/Module/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/Module/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/ModelStub.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/event/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/event/DeleteEventCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteModuleParserTest.java
  src/test/java/seedu/address/logic/parser/EditModuleParserTest.java
  src/test/java/seedu/address/logic/parser/ViewModuleParserTest.java
  src/test/java/seedu/address/logic/parser/event/AddEventParserTest.java
  src/test/java/seedu/address/logic/parser/event/DeleteEventParserTest.java
  src/test/java/seedu/address/logic/parser/event/EditEventParserTest.java
  src/test/java/seedu/address/logic/parser/event/FindEventParserTest.java
  src/test/java/seedu/address/logic/parser/event/ViewEventParserTest.java
  src/test/java/seedu/address/model/EventListTest.java
  src/test/java/seedu/address/model/event/EventContainsDatePredicateTest.java
  src/test/java/seedu/address/model/event/EventNameContainsKeyWordsPredicateTest.java
  src/test/java/seedu/address/model/event/EventNameTest.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/model/event/EventTimeTest.java
  src/test/java/seedu/address/model/event/FindEventCriteraTest.java
  src/test/java/seedu/address/storage/event/JsonAdaptedEventTest.java
  src/test/java/seedu/address/storage/event/JsonEventListStorageTest.java
  src/test/java/seedu/address/storage/event/JsonSerializableEventListTest.java
  src/test/java/seedu/address/testutil/event/EditEventDescriptorBuilder.java
  src/test/java/seedu/address/testutil/event/EventBuilder.java
  src/test/java/seedu/address/testutil/event/EventListBuilder.java
  src/test/java/seedu/address/testutil/event/EventUtil.java
  src/test/java/seedu/address/testutil/event/TypicalIndexes.java
Labels: priority.High, type.code

#559 Fix incorrect add module message usage
  src/main/java/seedu/address/logic/commands/modulelistcommands/AddModuleCommand.java
Labels: priority.Low, type.Bug

#582 GUI: Update contact card
  .github/workflows/gradle.yml
  src/main/java/seedu/address/logic/commands/contactlistcommands/AddContactCommand.java
  src/main/java/seedu/address/model/contact/Contact.java
  src/main/java/seedu/address/model/contact/ContactComparatorByName.java
  src/main/java/seedu/address/model/contact/ContactName.java
  src/main/java/seedu/address/model/contact/ContactNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/contact/Email.java
  src/main/java/seedu/address/storage/JsonAdaptedContact.java
  src/main/java/seedu/address/ui/ContactCard.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/ContactListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ModuleListCard.fxml
  src/main/resources/view/TodoListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.Medium, type.Enhancement, type.code

#600 Modify FindTaskCommand to enable searching by task status
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/todolistcommands/FindTaskCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/todolistparsers/FindTaskParser.java
  src/main/java/seedu/address/model/task/Status.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskMatchesStatusPredicate.java
Labels: priority.High, severity.Low, type.code

#605 First draft of PPP
  docs/AboutUs.md
  docs/team/jonasng.md
  docs/team/jonasngs.md
Labels: priority.High, type.documentation

#611 PPP : Create initial draft [Week 12 Requirement]
  docs/team/michael-setia.md
Labels: priority.High, type.Task, type.documentation

#612 V1.4 scheduler tests
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/schedulercommands/EditEventCommand.java
  src/main/java/seedu/address/model/event/EventTime.java
  src/test/java/seedu/address/logic/ModelStub.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/event/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/event/DeleteEventCommandTest.java
  src/test/java/seedu/address/logic/commands/event/EditEventCommandTest.java
  src/test/java/seedu/address/logic/commands/event/FindEventCommandTest.java
  src/test/java/seedu/address/testutil/event/EventUtil.java
  src/test/java/seedu/address/testutil/event/FindEventCriteriaBuilder.java
Labels: priority.High, type.code

#615 PPP : Create initial draft [Week 12 Requirement] for David
  docs/team/davidcaiqifan.md
Labels: priority.High, type.documentation

#579 Test : Module List storage tests
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/grade/AssignmentName.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/JsonAdaptedZoomLink.java
  src/main/java/seedu/address/storage/JsonSerializableModuleList.java
  src/test/data/JsonModuleListStorageTest/invalidAndValidModuleModuleList.json
  src/test/data/JsonModuleListStorageTest/invalidModuleModuleList.json
  src/test/data/JsonModuleListStorageTest/notJsonFormatModuleList.json
  src/test/data/JsonSerializableModuleListTest/duplicateModuleModuleList.json
  src/test/data/JsonSerializableModuleListTest/invalidModuleModuleList.json
  src/test/data/JsonSerializableModuleListTest/typicalModuleModuleList.json
  src/test/java/seedu/address/logic/commands/modulelistcommands/FindModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/modulelistcommands/HelpCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedModuleTest.java
  src/test/java/seedu/address/storage/JsonModuleListStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableModuleListTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/storage/module/JsonAdaptedAssignmentTest.java
  src/test/java/seedu/address/storage/module/JsonAdaptedGradeTrackerTest.java
  src/test/java/seedu/address/storage/module/JsonAdaptedModuleTest.java
  src/test/java/seedu/address/storage/module/JsonModuleListStorageTest.java
  src/test/java/seedu/address/storage/module/JsonSerializableModuleListTest.java
  src/test/java/seedu/address/testutil/EditModuleDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ModuleBuilder.java
  src/test/java/seedu/address/testutil/TypicalModules.java
Labels: priority.High, type.Task, type.code

#617 Add PPP Draft
  docs/AboutUs.md
  docs/team/murtubak.md
Labels: priority.High, type.documentation

#619 Updated Portfoilo
  docs/team/matthiaslhk.md
Labels: priority.High, type.documentation

#586 Add copy zoom link feature
  src/main/java/seedu/address/logic/commands/ViewCommandResult.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/ViewModuleCommand.java
  src/main/java/seedu/address/ui/AssignmentCard.java
  src/main/java/seedu/address/ui/DetailDisplay.java
  src/main/java/seedu/address/ui/DisplayZoomLink.java
  src/main/java/seedu/address/ui/ZoomLinkCard.java
  src/main/java/seedu/address/ui/ZoomLinkPanel.java
  src/main/resources/view/ZoomLinkCard.fxml
Labels: priority.High, type.code

#628 ContactList : Added exception when parsing "sortcontact" command
  src/main/java/seedu/address/logic/parser/contactlistparsers/SortContactParser.java
Labels: severity.High, type.Bug, type.code

#626 Add color change for detecting events
  src/main/java/seedu/address/model/event/EventTime.java
  src/main/java/seedu/address/ui/Calender.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.Medium, type.code

#602 Implement JUnit tests for Add Assignment Command
  src/main/java/seedu/address/logic/commands/gradetrackercommands/AddAssignmentCommand.java
  src/main/java/seedu/address/model/module/grade/Assignment.java
  src/main/java/seedu/address/model/module/grade/AssignmentResult.java
  src/main/java/seedu/address/model/module/grade/Grade.java
  src/main/java/seedu/address/model/module/grade/GradeTracker.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/gradetrackercommands/AddAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/gradetrackercommands/AddGradeCommandTest.java
  src/test/java/seedu/address/logic/commands/gradetrackercommands/DeleteAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/gradetrackercommands/EditAssignmentCommandTest.java
  src/test/java/seedu/address/logic/parser/gradetrackerparsers/AddAssignmentParserTest.java
  src/test/java/seedu/address/logic/parser/gradetrackerparsers/AddGradeParserTest.java
  src/test/java/seedu/address/logic/parser/gradetrackerparsers/DeleteAssignmentParserTest.java
  src/test/java/seedu/address/logic/parser/gradetrackerparsers/EditAssignmentParserTest.java
  src/test/java/seedu/address/model/module/gradetracker/AssignmentNameTest.java
  src/test/java/seedu/address/model/module/gradetracker/AssignmentNotFoundExceptionTest.java
  src/test/java/seedu/address/model/module/gradetracker/AssignmentPercentageTest.java
  src/test/java/seedu/address/model/module/gradetracker/AssignmentResultTest.java
  src/test/java/seedu/address/model/module/gradetracker/AssignmentTest.java
  src/test/java/seedu/address/model/module/gradetracker/DuplicateAssignmentExceptionTest.java
  src/test/java/seedu/address/model/module/gradetracker/GradeTest.java
  src/test/java/seedu/address/model/module/gradetracker/GradeTrackerTest.java
  src/test/java/seedu/address/testutil/AssignmentBuilder.java
  src/test/java/seedu/address/testutil/ModuleBuilder.java
  src/test/java/seedu/address/testutil/TypicalAssignments.java
  src/test/java/seedu/address/testutil/TypicalModules.java
Labels: priority.High, type.code

#607 Add test cases for contact list parsers
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/contactlistparsers/AddContactParserTest.java
  src/test/java/seedu/address/logic/parser/contactlistparsers/DeleteContactParserTest.java
  src/test/java/seedu/address/logic/parser/contactlistparsers/EditContactParserTest.java
  src/test/java/seedu/address/logic/parser/contactlistparsers/FindContactParserTest.java
  src/test/java/seedu/address/logic/parser/contactlistparsers/ImportantContactParserTest.java
  src/test/java/seedu/address/logic/parser/contactlistparsers/ResetContactParserTest.java
  src/test/java/seedu/address/logic/parser/contactlistparsers/SortContactParserTest.java
  src/test/java/seedu/address/testutil/TypicalContacts.java
Labels: priority.Medium, type.Task, type.code

#627 TodoList : Enable "edittask" command to delete details of a task
  src/main/java/seedu/address/logic/commands/todolistcommands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/todolistcommands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/todolistcommands/EditTaskDescriptor.java
  src/main/java/seedu/address/logic/parser/todolistparsers/EditTaskParser.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/resources/view/TodoListCard.fxml
Labels: priority.Medium, type.code

#609 Update gradetracker
  src/main/java/seedu/address/logic/commands/gradetrackercommands/AddAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/gradetrackercommands/AddGradeCommand.java
  src/main/java/seedu/address/logic/commands/gradetrackercommands/DeleteAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/gradetrackercommands/EditAssignmentCommand.java
  src/main/java/seedu/address/logic/parser/gradetrackerparsers/AddAssignmentParser.java
  src/main/java/seedu/address/model/module/grade/AssignmentResult.java
  src/main/java/seedu/address/model/module/grade/Grade.java
  src/main/java/seedu/address/model/module/grade/GradeTracker.java
Labels: priority.High, type.code

#598 Implement Junit tests for FindTaskCommand
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/model/event/EventTime.java
  src/main/java/seedu/address/model/task/FindTaskCriteria.java
  src/main/java/seedu/address/model/task/TaskMatchesPriorityPredicate.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/contactlistcommands/AddContactCommandTest.java
  src/test/java/seedu/address/logic/commands/contactlistcommands/ClearContactCommandTest.java
  src/test/java/seedu/address/logic/commands/contactlistcommands/DeleteContactCommandTest.java
  src/test/java/seedu/address/logic/commands/contactlistcommands/EditContactCommandTest.java
  src/test/java/seedu/address/logic/commands/contactlistcommands/EditContactDescriptorTest.java
  src/test/java/seedu/address/logic/commands/contactlistcommands/FindContactCommandTest.java
  src/test/java/seedu/address/logic/commands/contactlistcommands/ListContactCommandTest.java
  src/test/java/seedu/address/logic/commands/todolistcommands/FindTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/ModuleListParserTest.java
  src/test/java/seedu/address/logic/parser/contactlistparsers/AddContactParserTest.java
  src/test/java/seedu/address/logic/parser/contactlistparsers/EditContactParserTest.java
  src/test/java/seedu/address/model/ContactListTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/contact/ContactContainsTagsPredicateTest.java
  src/test/java/seedu/address/model/contact/ContactNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/contact/ContactTest.java
  src/test/java/seedu/address/model/contact/FindContactCriteriaTest.java
  src/test/java/seedu/address/model/contact/UniqueContactListTest.java
  src/test/java/seedu/address/model/task/FindTaskCriteriaTest.java
  src/test/java/seedu/address/model/task/TaskContainsTagsPredicateTest.java
  src/test/java/seedu/address/model/task/TaskMatchesDatePredicateTest.java
  src/test/java/seedu/address/model/task/TaskMatchesPriorityPredicateTest.java
  src/test/java/seedu/address/model/task/TaskMatchesStatusPredicateTest.java
  src/test/java/seedu/address/model/task/TaskNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/module/JsonAdaptedModuleTest.java
  src/test/java/seedu/address/testutil/contact/ContactBuilder.java
  src/test/java/seedu/address/testutil/contact/ContactListBuilder.java
  src/test/java/seedu/address/testutil/contact/ContactUtil.java
  src/test/java/seedu/address/testutil/contact/EditContactDescriptorBuilder.java
  src/test/java/seedu/address/testutil/contact/FindContactCriteriaBuilder.java
  src/test/java/seedu/address/testutil/contact/TypicalContacts.java
  src/test/java/seedu/address/testutil/todolist/FindTaskCriteriaBuilder.java
  src/test/java/seedu/address/testutil/todolist/TaskBuilder.java
Labels: priority.High, type.Task, type.code

#631 Test : Update test cases for versioned lists
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedContactList.java
  src/main/java/seedu/address/model/VersionedEventList.java
  src/main/java/seedu/address/model/VersionedModuleList.java
  src/main/java/seedu/address/model/VersionedTodoList.java
  src/test/java/seedu/address/model/VersionedContactListTest.java
  src/test/java/seedu/address/model/VersionedEventListTest.java
  src/test/java/seedu/address/model/VersionedModuleListTest.java
  src/test/java/seedu/address/model/VersionedTodoListTest.java
  src/test/java/seedu/address/testutil/todolist/TaskBuilder.java
Labels: priority.Medium, type.Task, type.code

#634 Tests : Update Junit tests for contact list storage component
  src/test/data/JsonContactListStorageTest/invalidAndValidContactContactList.json
  src/test/data/JsonContactListStorageTest/invalidContactContactList.json
  src/test/data/JsonContactListStorageTest/notJsonFormatContactList.json
  src/test/data/JsonSerializableContactListTest/duplicateContactContactList.json
  src/test/data/JsonSerializableContactListTest/invalidContactContactList.json
  src/test/data/JsonSerializableContactListTest/typicalContactContactList.json
  src/test/java/seedu/address/storage/contactliststorage/JsonAdaptedContactTest.java
  src/test/java/seedu/address/storage/contactliststorage/JsonContactListStorageTest.java
  src/test/java/seedu/address/storage/contactliststorage/JsonSerializableContactListTest.java
  src/test/java/seedu/address/storage/module/JsonAdaptedModuleTest.java
  src/test/java/seedu/address/storage/module/JsonModuleListStorageTest.java
Labels: priority.Medium, type.Task, type.code

#637 Test : Add test cases for Undo/Redo commands
  src/main/java/seedu/address/logic/commands/modulelistcommands/AddCompletedModuleCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/ArchiveModuleCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/UnarchiveModuleCommand.java
  src/main/java/seedu/address/model/VersionedModuleList.java
  src/main/java/seedu/address/model/module/Module.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/commands/modulelistcommands/AddCompletedModuleCommandTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.Medium, type.code

#642 Add tagging for events
  src/main/java/seedu/address/logic/commands/schedulercommands/EditEventCommand.java
  src/main/java/seedu/address/logic/parser/schedulerparsers/AddEventParser.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/ui/EventCard.java
  src/test/java/seedu/address/logic/commands/event/EditEventCommandTest.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/storage/event/JsonAdaptedEventTest.java
  src/test/java/seedu/address/storage/event/JsonEventListStorageTest.java
  src/test/java/seedu/address/testutil/event/EventBuilder.java
  src/test/java/seedu/address/testutil/event/EventUtil.java
Labels: priority.High, type.code

#645 V1.4 bug fix single word command
  src/main/java/seedu/address/logic/ParserManager.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/parser/GradeTrackerParser.java
  src/main/java/seedu/address/logic/parser/ModuleListParser.java
  src/main/java/seedu/address/logic/parser/SchedulerParser.java
  src/main/java/seedu/address/logic/parser/TodoListParser.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/ContactListParser.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/parser/ModuleListParserTest.java
Labels: priority.High, type.Bug, type.code

#658 Update UG
  docs/UserGuide.md
  docs/images/OverallGUISnapShot.png
  docs/images/OverallGUISnapShotWithLabels.png
Labels: priority.High, type.documentation

#655 Implement Junit tests for Zoom Link Command Parsers
  src/main/java/seedu/address/logic/ParserManager.java
  src/main/java/seedu/address/logic/parser/ContactListParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/EditZoomLinkParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/contactlistparsers/ContactListParserTest.java
  src/test/java/seedu/address/logic/parser/contactlistparsers/EditContactParserTest.java
  src/test/java/seedu/address/logic/parser/contactlistparsers/FindContactParserTest.java
  src/test/java/seedu/address/logic/parser/contactlistparsers/SortContactParserTest.java
  src/test/java/seedu/address/logic/parser/modulelistparsers/AddZoomLinkParserTest.java
  src/test/java/seedu/address/logic/parser/modulelistparsers/DeleteZoomLinkParserTest.java
  src/test/java/seedu/address/logic/parser/modulelistparsers/EditZoomLinkParserTest.java
Labels: priority.Medium, type.code

#629 Test : Add test for basic ModuleTracker commands
  src/test/java/seedu/address/logic/commands/AddModuleCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/modulelistcommands/AddModuleCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/modulelistcommands/AddModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/modulelistcommands/ClearModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/modulelistcommands/DeleteModuleCommandTest.java
Labels: priority.High, type.Task, type.code

#664 UG : Update for existing and new features
  docs/UserGuide.md
  src/main/java/seedu/address/logic/ParserManager.java
  src/main/java/seedu/address/logic/parser/ModuleListParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/FindModuleCommandParser.java
  src/test/java/seedu/address/logic/parser/FindModuleCommandParserTest.java
Labels: priority.Medium, type.documentation

#653 Add tests for EventContainsTagPredicate
  src/main/java/seedu/address/model/event/exceptions/EventDuplicateException.java
  src/main/java/seedu/address/model/event/exceptions/EventNotFoundException.java
  src/main/java/seedu/address/model/event/exceptions/EventOverlapException.java
  src/test/java/seedu/address/model/event/EventContainsTagsPredicateTest.java
  src/test/java/seedu/address/testutil/event/EventBuilder.java
Labels: priority.High, type.code

#649 Test : Add test cases for todo list storage
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/storage/JsonTodoListStorage.java
  src/test/data/JsonSerializableTodoListTest/duplicateTaskTodoList.json
  src/test/data/JsonSerializableTodoListTest/invalidTaskTodoList.json
  src/test/data/JsonSerializableTodoListTest/typicalTaskTodoList.json
  src/test/data/JsonTodoListStorageTest/invalidAndValidTaskTodoList.json
  src/test/data/JsonTodoListStorageTest/invalidTaskTodoList.json
  src/test/data/JsonTodoListStorageTest/notJsonFormatTodoList.json
  src/test/data/Module/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/Module/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/Module/JsonAddressBookStorageTest/notJsonFormatAddressBook.json
  src/test/data/Module/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/Module/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/Module/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/storage/contactliststorage/JsonContactListStorageTest.java
  src/test/java/seedu/address/storage/task/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/storage/task/JsonSerializableTodoListTest.java
  src/test/java/seedu/address/storage/task/JsonTodoListStorageTest.java
  src/test/java/seedu/address/testutil/todolist/TypicalTasks.java
Labels: priority.Medium, type.code

#665 V1.4 update DG for scheduler
  docs/DeveloperGuide.md
  docs/diagrams/event/AddEventCommandSequenceDiagram.puml
  docs/diagrams/event/AddEventSequenceDiagram.puml
  docs/diagrams/event/EventRelatedCommandsActivityDiagram.puml
  docs/images/AddEventSequenceDiagram.png
  docs/images/CalendarView.png
  src/main/java/seedu/address/logic/parser/ModuleListParser.java
  src/test/java/seedu/address/logic/parser/FindModuleCommandParserTest.java
Labels: priority.High, type.documentation

#651 Test : JUnit testing for gradetracker
  docs/DeveloperGuide.md
  docs/diagrams/model/AddAssignmentSequenceDiagram.puml
  docs/diagrams/model/ModuleListDiagram.puml
  docs/images/AddAssignmentSequenceDiagram.png
  docs/images/ModuleListDiagram.png
  src/main/java/seedu/address/logic/commands/ViewCommandResult.java
  src/main/java/seedu/address/logic/commands/gradetrackercommands/AddGradeCommand.java
  src/main/java/seedu/address/logic/commands/gradetrackercommands/DeleteAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/gradetrackercommands/EditAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/gradetrackercommands/EditAssignmentDescriptor.java
  src/main/java/seedu/address/logic/parser/gradetrackerparsers/EditAssignmentParser.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/UniqueModuleList.java
  src/main/java/seedu/address/model/module/exceptions/DuplicateModuleException.java
  src/main/java/seedu/address/model/module/exceptions/ModuleNotFoundException.java
  src/main/java/seedu/address/model/module/grade/GradeTracker.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ViewCommandResultTest.java
  src/test/java/seedu/address/logic/commands/gradetrackercommands/AddAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/gradetrackercommands/AddGradeCommandTest.java
  src/test/java/seedu/address/logic/commands/gradetrackercommands/DeleteAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/gradetrackercommands/EditAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/modulelistcommands/EditModuleCommandTest.java
  src/test/java/seedu/address/logic/parser/GradeTrackerParserTest.java
  src/test/java/seedu/address/logic/parser/ModuleListParserTest.java
  src/test/java/seedu/address/logic/parser/gradetrackerparsers/AddAssignmentParserTest.java
  src/test/java/seedu/address/logic/parser/gradetrackerparsers/AddGradeParserTest.java
  src/test/java/seedu/address/logic/parser/gradetrackerparsers/DeleteAssignmentParserTest.java
  src/test/java/seedu/address/logic/parser/gradetrackerparsers/EditAssignmentParserTest.java
  src/test/java/seedu/address/model/module/DuplicateModuleExceptionTest.java
  src/test/java/seedu/address/model/module/ModuleNotFoundExceptionTest.java
  src/test/java/seedu/address/model/module/gradetracker/AssignmentNotFoundExceptionTest.java
  src/test/java/seedu/address/model/module/gradetracker/AssignmentTest.java
  src/test/java/seedu/address/model/module/gradetracker/DuplicateAssignmentExceptionTest.java
  src/test/java/seedu/address/model/module/gradetracker/GradeTrackerTest.java
  src/test/java/seedu/address/storage/module/JsonSerializableModuleListTest.java
  src/test/java/seedu/address/testutil/ModuleBuilder.java
  src/test/java/seedu/address/testutil/ModuleUtil.java
  src/test/java/seedu/address/testutil/TypicalModules.java
  src/test/java/seedu/address/testutil/gradetracker/AssignmentBuilder.java
  src/test/java/seedu/address/testutil/gradetracker/AssignmentUtil.java
  src/test/java/seedu/address/testutil/gradetracker/EditAssignmentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/gradetracker/TypicalAssignments.java
Labels: priority.High, type.Bug

#659 Bugfix : Module Tracker regression bugs
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/AddZoomLinkCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/DeleteZoomLinkCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/EditModuleCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/EditZoomLinkCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/FindModuleParser.java
  src/main/java/seedu/address/logic/parser/ModuleListParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/EditModuleParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/FindModuleParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/RedoParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/UndoParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/ModuleCard.java
  src/main/java/seedu/address/ui/ModuleSmallDetailsCard.java
  src/main/resources/view/ModuleListCard.fxml
  src/main/resources/view/ModuleSmallDetailsCard.fxml
  src/test/java/seedu/address/logic/parser/FindModuleCommandParserTest.java
Labels: type.Bug, type.code

#685 Improve code quality for main module tracker features
  src/main/java/seedu/address/logic/commands/modulelistcommands/AddCompletedModuleCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/ArchiveModuleCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/CalculateCapCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/ClearModuleCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/EditModuleCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/EditModuleDescriptor.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/FindModuleCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/ListModuleCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/TargetCapCalculatorCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/UnarchiveModuleCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/ViewArchivedModulesCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/ViewModuleCommand.java
  src/main/java/seedu/address/logic/parser/ModuleListParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/AddCompletedModuleParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/AddModuleParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/ArchiveModuleParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/DeleteModuleParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/EditModuleParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/FindModuleParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/TargetCapCalculatorParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/UnarchiveModuleParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/ViewModuleParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedContactList.java
  src/main/java/seedu/address/model/VersionedEventList.java
  src/main/java/seedu/address/model/VersionedModuleList.java
  src/main/java/seedu/address/model/VersionedTodoList.java
  src/main/java/seedu/address/model/module/ModularCredits.java
  src/main/java/seedu/address/model/module/ModuleNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/module/grade/GradePoint.java
  src/main/java/seedu/address/storage/ArchivedModuleListStorage.java
  src/main/java/seedu/address/storage/ModuleListStorage.java
  src/main/java/seedu/address/storage/TodoListStorage.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/modulelistcommands/EditModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/modulelistcommands/EditModuleDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditModuleParserTest.java
  src/test/java/seedu/address/logic/parser/FindModuleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ModuleListParserTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/EditModuleDescriptorBuilder.java
Labels: priority.Medium, type.code

#632 Test : Add tests for all TodoList related code
  src/main/java/seedu/address/logic/commands/todolistcommands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/todolistcommands/FindTaskCommand.java
  src/main/java/seedu/address/logic/commands/todolistcommands/HelpTaskCommand.java
  src/main/java/seedu/address/logic/commands/todolistcommands/ViewTaskCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TodoListParser.java
  src/main/java/seedu/address/logic/parser/todolistparsers/SortTaskParser.java
  src/main/java/seedu/address/logic/parser/todolistparsers/ViewTaskParser.java
  src/main/java/seedu/address/model/task/Criterion.java
  src/main/java/seedu/address/model/task/Date.java
  src/main/java/seedu/address/model/task/Priority.java
  src/main/java/seedu/address/model/task/Status.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskName.java
  src/main/java/seedu/address/model/task/Type.java
  src/main/java/seedu/address/model/task/comparator/DateComparator.java
  src/main/java/seedu/address/model/task/comparator/TaskNameComparator.java
  src/test/data/JsonSerializableTodoListTest/typicalTaskTodoList.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/todolistcommands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/todolistcommands/ClearTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/todolistcommands/CompleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/todolistcommands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/todolistcommands/EditTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/todolistcommands/ListTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/todolistcommands/ResetTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/todolistcommands/SortTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/todolistparsers/AddTaskParserTest.java
  src/test/java/seedu/address/logic/parser/todolistparsers/CompleteTaskParserTest.java
  src/test/java/seedu/address/logic/parser/todolistparsers/DeleteTaskParserTest.java
  src/test/java/seedu/address/logic/parser/todolistparsers/EditTaskParserTest.java
  src/test/java/seedu/address/logic/parser/todolistparsers/FindTaskParserTest.java
  src/test/java/seedu/address/logic/parser/todolistparsers/ResetTaskParserTest.java
  src/test/java/seedu/address/logic/parser/todolistparsers/SortTaskParserTest.java
  src/test/java/seedu/address/logic/parser/todolistparsers/TodoListParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/TodoListTest.java
  src/test/java/seedu/address/model/task/CriterionTest.java
  src/test/java/seedu/address/model/task/DateTest.java
  src/test/java/seedu/address/model/task/PriorityTest.java
  src/test/java/seedu/address/model/task/StatusTest.java
  src/test/java/seedu/address/model/task/TaskNameTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/model/task/UniqueTodoListTest.java
  src/test/java/seedu/address/model/task/comparator/DateComparatorTest.java
  src/test/java/seedu/address/model/task/comparator/TaskComparatorByDateTest.java
  src/test/java/seedu/address/model/task/comparator/TaskComparatorByNameTest.java
  src/test/java/seedu/address/model/task/comparator/TaskComparatorByPriorityTest.java
  src/test/java/seedu/address/model/task/comparator/TaskNameComparatorTest.java
  src/test/java/seedu/address/storage/task/JsonSerializableTodoListTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/todolist/EditTaskDescriptorBuilder.java
  src/test/java/seedu/address/testutil/todolist/EditTaskDescriptorTest.java
  src/test/java/seedu/address/testutil/todolist/TaskBuilder.java
  src/test/java/seedu/address/testutil/todolist/TaskUtil.java
  src/test/java/seedu/address/testutil/todolist/TypicalTasks.java
Labels: priority.High, type.Task, type.code

#683 V1.4 gui view bug fix
  src/main/java/seedu/address/model/module/grade/Grade.java
  src/main/java/seedu/address/ui/ModuleCard.java
  src/main/java/seedu/address/ui/ModuleSmallDetailsCard.java
  src/main/resources/view/ModuleListCard.fxml
  src/main/resources/view/ModuleSmallDetailsCard.fxml
Labels: priority.High, type.Bug, type.code

#650 Add test cases for logic manager
  docs/DeveloperGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: priority.Medium, type.code

#676 Test : Add tests for ContactList
  src/test/java/seedu/address/logic/commands/contactlistcommands/ImportantContactCommandTest.java
  src/test/java/seedu/address/logic/commands/contactlistcommands/ResetContactCommandTest.java
  src/test/java/seedu/address/logic/commands/contactlistcommands/SortContactCommandTest.java
  src/test/java/seedu/address/logic/parser/contactlistparsers/SortContactParserTest.java
Labels: priority.High, type.Task, type.code

#690 Finalize PPP
  docs/team/davidcaiqifan.md
Labels: priority.High, type.documentation

#672 Fix bug with grades
  src/main/java/seedu/address/logic/commands/gradetrackercommands/AddAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/gradetrackercommands/AddGradeCommand.java
  src/main/java/seedu/address/logic/commands/gradetrackercommands/DeleteAssignmentCommand.java
Labels: priority.High, severity.High, type.Bug

#687 V1.4 update dg 2
  docs/DeveloperGuide.md
  docs/diagrams/event/AddEventCommandSequenceDiagram.puml
  docs/diagrams/event/AddEventSequenceDiagram.puml
  docs/diagrams/event/GeneralLogicSequenceDiagram1.puml
  docs/diagrams/event/GeneralLogicSequenceDiagram2.puml
  docs/diagrams/model/EventListClassDiagram.puml
  docs/images/AddEventSequenceDiagram.png
  docs/images/EventListClassDiagram.png
  docs/images/GeneralLogicSequenceDiagram1.png
  docs/images/GeneralLogicSequenceDiagram2.png
Labels: priority.High, type.documentation

#697 Fix bug from ContactList tests
  src/test/java/seedu/address/logic/commands/contactlistcommands/ImportantContactCommandTest.java
  src/test/java/seedu/address/logic/commands/contactlistcommands/ResetContactCommandTest.java
Labels: severity.High, type.Bug

#695 Update UG for recommited features
  docs/UserGuide.md
  src/main/java/seedu/address/logic/ParserManager.java
Labels: priority.Medium, type.documentation

#699 V1.4 update dg 2
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
Labels: priority.High, type.documentation

#693 Final PPP ND BUGFIX
  docs/team/matthiaslhk.md
  src/main/resources/view/ModuleListCard.fxml
Labels: priority.High, type.documentation

#701 BugFix
  docs/images/OverallGUISnapShot.png
  docs/images/Ui.png
  src/main/java/seedu/address/logic/commands/schedulercommands/DeleteEventCommand.java
Labels: priority.High, type.code, type.documentation

#691 Finalise PPP
  docs/team/jonasngs.md
  src/main/java/seedu/address/model/contact/Contact.java
Labels: priority.High, type.documentation

#705 Update portfolio
  docs/team/jonasngs.md
Labels: priority.High

#706 Update PPP
  docs/team/murtubak.md
Labels: priority.High, type.documentation

#689 DG updates
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/gradetracker/DeleteAssignmentSequenceDiagram.puml
  docs/diagrams/gradetracker/EditAssignmentSequenceDiagram.puml
  docs/diagrams/gradetracker/GradeTrackerDiagram.puml
  docs/diagrams/model/AddAssignmentSequenceDiagram.puml
  docs/diagrams/model/ContactListDiagram.puml
  docs/diagrams/model/GradeTrackerDiagram.puml
  docs/images/ContactListDiagram.png
  docs/images/GradeTracker/DeleteAssignmentCommandSequenceDiagram.png
  docs/images/GradeTracker/EditAssignmentSequenceDiagram.png
  docs/images/GradeTracker/GradeTrackerDiagram.png
  docs/images/GradeTrackerDiagram.png
  src/main/java/seedu/address/logic/commands/gradetrackercommands/AddAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/gradetrackercommands/EditAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/gradetrackercommands/EditAssignmentDescriptor.java
  src/main/java/seedu/address/logic/parser/gradetrackerparsers/EditAssignmentParser.java
  src/test/java/seedu/address/logic/commands/gradetrackercommands/EditAssignmentCommandTest.java
  src/test/java/seedu/address/logic/parser/GradeTrackerParserTest.java
  src/test/java/seedu/address/logic/parser/gradetrackerparsers/EditAssignmentParserTest.java
  src/test/java/seedu/address/testutil/gradetracker/EditAssignmentDescriptorBuilder.java
Labels: priority.High, type.documentation

#678 DG : Finalize for submission
  docs/DeveloperGuide.md
  docs/diagrams/task/AddTaskSequenceDiagram.puml
  docs/diagrams/task/EditTaskCommandSequenceDiagram.puml
  docs/diagrams/task/EditTaskDeleteFieldActivityDiagram.puml
  docs/diagrams/task/SortTaskCommandSequenceDiagram.puml
  docs/diagrams/task/TaskClassDiagram.puml
  docs/diagrams/task/TaskComparatorClassDiagram.puml
  docs/images/Task/TaskClassDiagram.png
  docs/images/Task/TaskComparatorClassDiagram.png
  docs/images/TodoList/AddTaskSequenceDiagram.png
  docs/images/TodoList/EditTaskCommandSequenceDiagram.png
  docs/images/TodoList/EditTaskDeleteFieldActivityDiagram.png
  docs/images/TodoList/SortTaskCommandSequenceDiagram.png
Labels: priority.High, type.Task, type.documentation

#713 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/model/ModuleListClassDiagram.puml
  docs/images/Module/ModuleListClassDiagram.png
  docs/images/ModuleListDiagram.png
Labels: priority.Medium, type.documentation

#709 V1.4 update ug 2
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/AddEventExample.png
  docs/images/EditEventExample.png
  docs/images/TpLogo.png
  docs/images/UG_OriginalTab.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/parser/schedulerparsers/EditEventParser.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/TpLogo.png
Labels: priority.High, type.documentation

#714 Update UG with images
  docs/UserGuide.md
  docs/images/addmodule.png
  docs/images/archivemodule.png
  docs/images/findmodule.png
  docs/images/viewmodule.png
Labels: priority.High, type.documentation

#710 Fix for missing JavaDocs
  src/main/java/seedu/address/logic/commands/contactlistcommands/SortContactCommand.java
  src/main/java/seedu/address/logic/commands/gradetrackercommands/AddAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/gradetrackercommands/AddGradeCommand.java
  src/main/java/seedu/address/logic/commands/gradetrackercommands/DeleteAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/gradetrackercommands/EditAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/schedulercommands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/schedulercommands/EditEventCommand.java
  src/main/java/seedu/address/logic/commands/schedulercommands/FindEventCommand.java
  src/main/java/seedu/address/logic/commands/schedulercommands/ViewEventCommand.java
  src/main/java/seedu/address/logic/commands/todolistcommands/HelpTaskCommand.java
  src/main/java/seedu/address/logic/parser/FeatureParser.java
  src/main/java/seedu/address/logic/parser/TodoListParser.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/ImportantContactParser.java
  src/main/java/seedu/address/logic/parser/gradetrackerparsers/AddAssignmentParser.java
  src/main/java/seedu/address/logic/parser/gradetrackerparsers/AddGradeParser.java
  src/main/java/seedu/address/logic/parser/gradetrackerparsers/DeleteAssignmentParser.java
  src/main/java/seedu/address/logic/parser/gradetrackerparsers/EditAssignmentParser.java
  src/main/java/seedu/address/logic/parser/schedulerparsers/AddEventParser.java
  src/main/java/seedu/address/logic/parser/schedulerparsers/DeleteEventParser.java
  src/main/java/seedu/address/logic/parser/schedulerparsers/EditEventParser.java
  src/main/java/seedu/address/logic/parser/schedulerparsers/FindEventParser.java
  src/main/java/seedu/address/logic/parser/schedulerparsers/ViewEventParser.java
  src/main/java/seedu/address/model/EventList.java
  src/main/java/seedu/address/model/event/EventContainsDatePredicate.java
  src/main/java/seedu/address/model/event/EventContainsTagsPredicate.java
  src/main/java/seedu/address/model/event/EventNameContainsKeyWordsPredicate.java
  src/main/java/seedu/address/model/event/FindEventCriteria.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/main/java/seedu/address/model/module/grade/AssignmentPercentage.java
  src/main/java/seedu/address/model/module/grade/AssignmentResult.java
  src/main/java/seedu/address/storage/JsonAdaptedAssignment.java
  src/main/java/seedu/address/storage/JsonEventListStorage.java
  src/main/java/seedu/address/storage/JsonModuleListStorage.java
  src/main/java/seedu/address/storage/JsonSerializableEventList.java
  src/main/java/seedu/address/storage/JsonTodoListStorage.java
  src/main/java/seedu/address/ui/AssignmentPanel.java
  src/main/java/seedu/address/ui/Calender.java
  src/main/java/seedu/address/ui/ContactListPanel.java
  src/main/java/seedu/address/ui/DetailDisplay.java
  src/main/java/seedu/address/ui/EventListPanel.java
  src/main/java/seedu/address/ui/TodoListPanel.java
  src/main/java/seedu/address/ui/ZoomLinkPanel.java
  src/test/java/seedu/address/logic/parser/todolistparsers/TodoListParserTest.java
Labels: priority.Low, type.documentation

#681 Update developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/contact/AddContactSequenceDiagram.puml
  docs/diagrams/contact/EditContactCommandActivityDiagram.puml
  docs/diagrams/contact/EditContactDescriptorClassDiagram.puml
  docs/diagrams/model/ContactListDiagram.puml
  docs/images/Contact/EditContactDescriptorClassDiagram.png
  docs/images/ContactListDiagram.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.High, type.documentation

#716 Update UG
  docs/UserGuide.md
  docs/images/GradeTracker/AddAssignment.PNG
  docs/images/GradeTracker/AddGrade.PNG
  src/main/java/seedu/address/logic/ParserManager.java
Labels: priority.Low, type.documentation

#720 Bugfix delete assignment
  src/main/java/seedu/address/logic/commands/gradetrackercommands/DeleteAssignmentCommand.java
  src/test/java/seedu/address/logic/commands/gradetrackercommands/DeleteAssignmentCommandTest.java
Labels: priority.High, type.Bug

#721 Update DG
  docs/DeveloperGuide.md
Labels: priority.High

#723 Fix images in UG
  docs/UserGuide.md
  docs/images/GradeTracker/AddAssignment.png
  docs/images/GradeTracker/AddGrade.png
Labels: priority.Medium, type.documentation

#725 Update UG
  docs/UserGuide.md
Labels: type.documentation
