Repository AY2021S1-CS2103T-F12-3/tp, pull requests merged in 2020-10, with the labels that each got.

#137 V1.2 update tokenizer to fit SLAP and changed Add module parser and Command
  src/main/java/tp/cap5buddy/logic/commands/AddModuleCommand.java
  src/main/java/tp/cap5buddy/logic/parser/AddModuleParser.java
  src/main/java/tp/cap5buddy/logic/parser/AddZoomLinkParser.java
  src/main/java/tp/cap5buddy/logic/parser/ParserManager.java
  src/main/java/tp/cap5buddy/logic/parser/PrefixPosition.java
  src/main/java/tp/cap5buddy/logic/parser/Tokenizer.java
Labels: priority.High, type.Task, type.code

#146 Implement add contact command for Contact List
  src/main/java/tp/cap5buddy/Cap5buddy.java
  src/main/java/tp/cap5buddy/contacts/Contact.java
  src/main/java/tp/cap5buddy/contacts/ContactList.java
  src/main/java/tp/cap5buddy/contacts/Email.java
  src/main/java/tp/cap5buddy/contacts/Name.java
  src/main/java/tp/cap5buddy/contacts/exceptions/ContactNotFoundException.java
  src/main/java/tp/cap5buddy/contacts/exceptions/DuplicateContactException.java
  src/main/java/tp/cap5buddy/logic/Logic.java
  src/main/java/tp/cap5buddy/logic/LogicManager.java
  src/main/java/tp/cap5buddy/logic/commands/AddContactCommand.java
  src/main/java/tp/cap5buddy/logic/commands/AddModuleCommand.java
  src/main/java/tp/cap5buddy/logic/commands/AddZoomLinkCommand.java
  src/main/java/tp/cap5buddy/logic/commands/Command.java
  src/main/java/tp/cap5buddy/logic/commands/CommandResult.java
  src/main/java/tp/cap5buddy/logic/commands/DeleteModuleCommand.java
  src/main/java/tp/cap5buddy/logic/commands/EditModuleCommand.java
  src/main/java/tp/cap5buddy/logic/commands/ViewModuleCommand.java
  src/main/java/tp/cap5buddy/logic/parser/AddContactParser.java
  src/main/java/tp/cap5buddy/logic/parser/AddZoomLinkParser.java
  src/main/java/tp/cap5buddy/logic/parser/ParserManager.java
  src/main/java/tp/cap5buddy/logic/parser/Prefix.java
  src/main/java/tp/cap5buddy/logic/parser/PrefixList.java
Labels: priority.High, type.Task, type.code

#139 V1.2 update tokenizer b
  src/main/java/tp/cap5buddy/logic/commands/ViewModuleCommand.java
  src/main/java/tp/cap5buddy/logic/parser/AddModuleParser.java
  src/main/java/tp/cap5buddy/logic/parser/DeleteModuleParser.java
  src/main/java/tp/cap5buddy/logic/parser/EditModuleParser.java
  src/main/java/tp/cap5buddy/logic/parser/ParserManager.java
  src/main/java/tp/cap5buddy/logic/parser/ViewModuleParser.java
Labels: priority.High, type.Task, type.code

#152 Implement delete contact command for contact list
  src/main/java/tp/cap5buddy/contacts/ContactList.java
  src/main/java/tp/cap5buddy/logic/commands/DeleteContactCommand.java
  src/main/java/tp/cap5buddy/logic/parser/DeleteContactParser.java
  src/main/java/tp/cap5buddy/logic/parser/ParserManager.java
Labels: priority.High, type.code

#154 Implement edit contact command for contact list
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/tp/cap5buddy/logic/commands/EditContactCommand.java
  src/main/java/tp/cap5buddy/logic/parser/EditContactParser.java
  src/main/java/tp/cap5buddy/logic/parser/ParserManager.java
  src/main/java/tp/cap5buddy/logic/parser/ParserUtil.java
Labels: priority.High, type.code

#158 Add base code and implement "add" and "view" feature for todo list
  src/main/java/tp/cap5buddy/Cap5buddy.java
  src/main/java/tp/cap5buddy/logic/LogicManager.java
  src/main/java/tp/cap5buddy/logic/commands/AddContactCommand.java
  src/main/java/tp/cap5buddy/logic/commands/AddModuleCommand.java
  src/main/java/tp/cap5buddy/logic/commands/AddTaskCommand.java
  src/main/java/tp/cap5buddy/logic/commands/AddZoomLinkCommand.java
  src/main/java/tp/cap5buddy/logic/commands/Command.java
  src/main/java/tp/cap5buddy/logic/commands/DeleteContactCommand.java
  src/main/java/tp/cap5buddy/logic/commands/DeleteModuleCommand.java
  src/main/java/tp/cap5buddy/logic/commands/EditContactCommand.java
  src/main/java/tp/cap5buddy/logic/commands/EditModuleCommand.java
  src/main/java/tp/cap5buddy/logic/commands/ViewModuleCommand.java
  src/main/java/tp/cap5buddy/logic/commands/ViewTodoListCommand.java
  src/main/java/tp/cap5buddy/logic/parser/AddTaskParser.java
  src/main/java/tp/cap5buddy/logic/parser/ParserManager.java
  src/main/java/tp/cap5buddy/logic/parser/Prefix.java
  src/main/java/tp/cap5buddy/logic/parser/PrefixList.java
  src/main/java/tp/cap5buddy/logic/parser/Tokenizer.java
  src/main/java/tp/cap5buddy/logic/parser/ViewTodoListParser.java
  src/main/java/tp/cap5buddy/todolist/Criterion.java
  src/main/java/tp/cap5buddy/todolist/Date.java
  src/main/java/tp/cap5buddy/todolist/DateComparator.java
  src/main/java/tp/cap5buddy/todolist/Description.java
  src/main/java/tp/cap5buddy/todolist/DescriptionComparator.java
  src/main/java/tp/cap5buddy/todolist/ParserUtilTodoList.java
  src/main/java/tp/cap5buddy/todolist/Priority.java
  src/main/java/tp/cap5buddy/todolist/Status.java
  src/main/java/tp/cap5buddy/todolist/Task.java
  src/main/java/tp/cap5buddy/todolist/TaskComparatorByDate.java
  src/main/java/tp/cap5buddy/todolist/TaskComparatorByDescription.java
  src/main/java/tp/cap5buddy/todolist/TaskComparatorByPriority.java
  src/main/java/tp/cap5buddy/todolist/TodoList.java
  src/main/java/tp/cap5buddy/todolist/Type.java
  src/main/java/tp/cap5buddy/todolist/exception/DuplicateTaskException.java
  src/main/java/tp/cap5buddy/todolist/exception/TaskNotFoundException.java
Labels: type.Task, type.code

#166 Implement delete task feature for TodoList
  src/main/java/tp/cap5buddy/logic/commands/DeleteTaskCommand.java
  src/main/java/tp/cap5buddy/logic/parser/DeleteTaskParser.java
  src/main/java/tp/cap5buddy/logic/parser/ParserManager.java
Labels: priority.High, type.Task, type.code

#169 Implement edit task feature for TodoList
  src/main/java/tp/cap5buddy/logic/commands/EditTaskCommand.java
  src/main/java/tp/cap5buddy/logic/parser/EditTaskParser.java
  src/main/java/tp/cap5buddy/logic/parser/ParserManager.java
Labels: priority.High, type.Task, type.code

#156 Implement find contact command for contact list
  src/main/java/tp/cap5buddy/logic/commands/FindContactCommand.java
  src/main/java/tp/cap5buddy/logic/parser/FindContactParser.java
  src/main/java/tp/cap5buddy/logic/parser/ParserManager.java
  src/main/java/tp/cap5buddy/logic/parser/Prefix.java
  src/main/java/tp/cap5buddy/logic/parser/PrefixList.java
Labels: priority.High, type.code

#188 Rename all instances of AddressBook to ModuleList
  docs/diagrams/ArchitectureSequenceDiagram.puml
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ModuleList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/tp/cap5buddy/storage/ModuleListStorage.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/ModuleListTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Task, type.code

#190 Safe delete Address class and all its dependencies
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ModuleListTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.code

#197 Refactor classes in Model package
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ModuleList.java
  src/main/java/seedu/address/model/ReadOnlyModuleList.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/UniqueModuleList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/ModuleListTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Task, type.code

#199 Safe delete Phone class and all of its dependencies
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Task

#210 v1.2 Storage Package Refactoring
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyModuleList.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonModuleListStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/JsonSerializableModuleList.java
  src/main/java/seedu/address/storage/ModuleListStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/storage/JsonAdaptedModuleTest.java
  src/test/java/seedu/address/storage/JsonModuleListStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableModuleListTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.High, type.Task, type.code

#218 V1.2 gui refactor
  src/main/java/seedu/address/model/module/ZoomLink.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ModuleCard.java
  src/main/java/seedu/address/ui/ModuleListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MainWindowOld.fxml
  src/main/resources/view/ModuleListCard.fxml
Labels: priority.High, type.code

#220 Rename shadowJar file name to cap5buddy
  build.gradle
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
Labels: priority.High

#222 V1.2 GUI Resize feature
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, type.code

#223 Refactor Person class into Contact class
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/contact/Contact.java
  src/main/java/seedu/address/model/contact/Email.java
  src/main/java/seedu/address/model/contact/Name.java
  src/main/java/seedu/address/model/contact/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/contact/Telegram.java
  src/main/java/seedu/address/model/contact/UniqueContactList.java
  src/main/java/seedu/address/model/contact/exceptions/ContactNotFoundException.java
  src/main/java/seedu/address/model/contact/exceptions/DuplicateContactException.java
  src/main/java/seedu/address/model/module/UniqueModuleList.java
  src/main/java/seedu/address/model/person/exceptions/PersonNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ModuleListTest.java
  src/test/java/seedu/address/model/contact/AddressTest.java
  src/test/java/seedu/address/model/contact/EmailTest.java
  src/test/java/seedu/address/model/contact/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/contact/NameTest.java
  src/test/java/seedu/address/model/contact/PersonTest.java
  src/test/java/seedu/address/model/contact/PhoneTest.java
  src/test/java/seedu/address/model/contact/UniquePersonListTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/ContactBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Task, type.code

#235 V1.3 Update Matt Portfolio
  docs/DeveloperGuide.md
  docs/images/OverViewClassDiagram.png
  docs/team/matthiaslhk.md
Labels: priority.High, type.Task

#209 Refactor testutil, ModuleListTest, ModelManagerTest and add necessary classes for Module testing
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/ModuleListTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/EditModuleDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ModuleBuilder.java
  src/test/java/seedu/address/testutil/ModuleListBuilder.java
  src/test/java/seedu/address/testutil/TypicalModules.java
Labels: type.Task, type.code

#226 Refactor Task class and its dependencies to match current version
  src/main/java/seedu/address/model/task/Criterion.java
  src/main/java/seedu/address/model/task/Date.java
  src/main/java/seedu/address/model/task/Priority.java
  src/main/java/seedu/address/model/task/Status.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskName.java
  src/main/java/seedu/address/model/task/Type.java
  src/main/java/seedu/address/model/task/comparator/DateComparator.java
  src/main/java/seedu/address/model/task/comparator/TaskComparatorByDate.java
  src/main/java/seedu/address/model/task/comparator/TaskComparatorByName.java
  src/main/java/seedu/address/model/task/comparator/TaskComparatorByPriority.java
  src/main/java/seedu/address/model/task/comparator/TaskNameComparator.java
Labels: priority.High, type.Task, type.code

#239 V1.3 logic refactor
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/commands/EditModuleCommand.java
  src/main/java/seedu/address/logic/commands/ViewModuleCommand.java
  src/main/java/seedu/address/logic/parser/AddModuleParser.java
  src/main/java/seedu/address/logic/parser/AddZoomLinkParser.java
  src/main/java/seedu/address/logic/parser/DeleteModuleParser.java
  src/main/java/seedu/address/logic/parser/EditModuleParser.java
  src/main/java/seedu/address/logic/parser/ModuleListParser.java
  src/main/java/seedu/address/logic/parser/ViewModuleParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/EditModuleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddModuleParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteModuleParserTest.java
  src/test/java/seedu/address/logic/parser/EditModuleParserTest.java
  src/test/java/seedu/address/logic/parser/ModuleListParserTest.java
  src/test/java/seedu/address/testutil/EditModuleDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High, type.Task, type.code

#228 Implement ContactList to encapsulate Contact related objects and methods
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/ContactList.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/ReadOnlyContactList.java
  src/main/java/seedu/address/model/contact/UniqueContactList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/EditModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/contact/UniquePersonListTest.java
Labels: priority.High, type.Task, type.code

#249 Implement add contact command for ContactList
  src/main/java/seedu/address/logic/commands/AddContactCommand.java
  src/main/java/seedu/address/logic/parser/AddContactParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ModuleListParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/contact/Contact.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/DeleteModuleCommandTest.java
  src/test/java/seedu/address/model/contact/PersonTest.java
  src/test/java/seedu/address/testutil/ContactBuilder.java
Labels: priority.High, type.Task, type.code

#250 Implement edit contact command for ContactList
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditContactCommand.java
  src/main/java/seedu/address/logic/commands/EditContactDescriptor.java
  src/main/java/seedu/address/logic/parser/EditContactParser.java
  src/main/java/seedu/address/logic/parser/ModuleListParser.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.High, type.Task, type.code

#229 Add TodoList class and its dependencies that match the current implementation
  src/main/java/seedu/address/model/ReadOnlyTodoList.java
  src/main/java/seedu/address/model/TodoList.java
  src/main/java/seedu/address/model/task/UniqueTodoList.java
  src/main/java/seedu/address/model/task/exceptions/DuplicateTaskException.java
  src/main/java/seedu/address/model/task/exceptions/TaskNotFoundException.java
Labels: priority.High, type.Task, type.code

#231 Implement sort methods for TodoList
  src/main/java/seedu/address/model/TodoList.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/UniqueTodoList.java
Labels: priority.High, type.Task, type.code

#246 Add ContactListParser, Contact related Parsers and Commands
  src/main/java/seedu/address/logic/commands/contactlistcommands/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/contactlistcommands/DeleteContactCommand.java
  src/main/java/seedu/address/logic/commands/contactlistcommands/EditContactCommand.java
  src/main/java/seedu/address/logic/commands/contactlistcommands/FindContactCommand.java
  src/main/java/seedu/address/logic/commands/contactlistcommands/HelpContactCommand.java
  src/main/java/seedu/address/logic/commands/contactlistcommands/ListContactCommand.java
  src/main/java/seedu/address/logic/commands/contactlistcommands/ViewContactCommand.java
  src/main/java/seedu/address/logic/parser/ContactListParser.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/AddContactParser.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/DeleteContactParser.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/EditContactParser.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/FindContactParser.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/ViewContactParser.java
Labels: priority.High, type.Task, type.code

#263 Delete AppStarter.java, Cap5buddy.java, MainApp.java from former package
  src/main/java/tp/cap5buddy/AppStarter.java
  src/main/java/tp/cap5buddy/Cap5buddy.java
  src/main/java/tp/cap5buddy/MainApp.java
  src/main/java/tp/cap5buddy/ui/gui/UiPart.java
Labels: type.Task, type.code

#265 Delete tp UI and FXML files
  src/main/java/tp/cap5buddy/ui/Messages.java
  src/main/java/tp/cap5buddy/ui/Ui.java
  src/main/java/tp/cap5buddy/ui/gui/MainWindow.java
  src/main/java/tp/cap5buddy/ui/gui/MainWindowController.java
  src/main/java/tp/cap5buddy/ui/gui/MainWindowResult.java
  src/main/java/tp/cap5buddy/ui/gui/Ui.java
  src/main/java/tp/cap5buddy/ui/gui/UiManager.java
  src/main/java/tp/cap5buddy/ui/gui/UiPart.java
  src/main/resources/view/tp/MainWindow.fxml
  src/main/resources/view/tp/MainWindowOLD.fxml
  src/main/resources/view/tp/MainWindowResult - Copy.fxml
  src/main/resources/view/tp/MainWindowResult.fxml
Labels: priority.High

#267 Delete Logic and TodoList
  src/main/java/tp/cap5buddy/logic/Logic.java
  src/main/java/tp/cap5buddy/logic/LogicManager.java
  src/main/java/tp/cap5buddy/logic/commands/AddContactCommand.java
  src/main/java/tp/cap5buddy/logic/commands/AddFinalGradeCommand.java
  src/main/java/tp/cap5buddy/logic/commands/AddGradeCommand.java
  src/main/java/tp/cap5buddy/logic/commands/AddModuleCommand.java
  src/main/java/tp/cap5buddy/logic/commands/AddTaskCommand.java
  src/main/java/tp/cap5buddy/logic/commands/AddZoomLinkCommand.java
  src/main/java/tp/cap5buddy/logic/commands/Command.java
  src/main/java/tp/cap5buddy/logic/commands/CommandResult.java
  src/main/java/tp/cap5buddy/logic/commands/DeleteContactCommand.java
  src/main/java/tp/cap5buddy/logic/commands/DeleteModuleCommand.java
  src/main/java/tp/cap5buddy/logic/commands/DeleteTaskCommand.java
  src/main/java/tp/cap5buddy/logic/commands/EditContactCommand.java
  src/main/java/tp/cap5buddy/logic/commands/EditModuleCommand.java
  src/main/java/tp/cap5buddy/logic/commands/EditTaskCommand.java
  src/main/java/tp/cap5buddy/logic/commands/FindContactCommand.java
  src/main/java/tp/cap5buddy/logic/commands/ViewModuleCommand.java
  src/main/java/tp/cap5buddy/logic/commands/ViewTodoListCommand.java
  src/main/java/tp/cap5buddy/logic/commands/exception/CommandException.java
  src/main/java/tp/cap5buddy/logic/parser/AddContactParser.java
  src/main/java/tp/cap5buddy/logic/parser/AddFinalGradeParser.java
  src/main/java/tp/cap5buddy/logic/parser/AddGradeParser.java
  src/main/java/tp/cap5buddy/logic/parser/AddModuleParser.java
  src/main/java/tp/cap5buddy/logic/parser/AddTaskParser.java
  src/main/java/tp/cap5buddy/logic/parser/AddZoomLinkParser.java
  src/main/java/tp/cap5buddy/logic/parser/ArgumentMap.java
  src/main/java/tp/cap5buddy/logic/parser/DeleteContactParser.java
  src/main/java/tp/cap5buddy/logic/parser/DeleteModuleParser.java
  src/main/java/tp/cap5buddy/logic/parser/DeleteTaskParser.java
  src/main/java/tp/cap5buddy/logic/parser/EditContactParser.java
  src/main/java/tp/cap5buddy/logic/parser/EditModuleParser.java
  src/main/java/tp/cap5buddy/logic/parser/EditTaskParser.java
  src/main/java/tp/cap5buddy/logic/parser/FindContactParser.java
  src/main/java/tp/cap5buddy/logic/parser/Parser.java
  src/main/java/tp/cap5buddy/logic/parser/ParserManager.java
  src/main/java/tp/cap5buddy/logic/parser/ParserUtil.java
  src/main/java/tp/cap5buddy/logic/parser/Prefix.java
  src/main/java/tp/cap5buddy/logic/parser/PrefixList.java
  src/main/java/tp/cap5buddy/logic/parser/PrefixPosition.java
  src/main/java/tp/cap5buddy/logic/parser/Tokenizer.java
  src/main/java/tp/cap5buddy/logic/parser/ViewModuleParser.java
  src/main/java/tp/cap5buddy/logic/parser/ViewTodoListParser.java
  src/main/java/tp/cap5buddy/logic/parser/exception/ParseException.java
  src/main/java/tp/cap5buddy/todolist/Criterion.java
  src/main/java/tp/cap5buddy/todolist/Date.java
  src/main/java/tp/cap5buddy/todolist/DateComparator.java
  src/main/java/tp/cap5buddy/todolist/Description.java
  src/main/java/tp/cap5buddy/todolist/DescriptionComparator.java
  src/main/java/tp/cap5buddy/todolist/ParserUtilTodoList.java
  src/main/java/tp/cap5buddy/todolist/Priority.java
  src/main/java/tp/cap5buddy/todolist/Status.java
  src/main/java/tp/cap5buddy/todolist/Task.java
  src/main/java/tp/cap5buddy/todolist/TaskComparatorByDate.java
  src/main/java/tp/cap5buddy/todolist/TaskComparatorByDescription.java
  src/main/java/tp/cap5buddy/todolist/TaskComparatorByPriority.java
  src/main/java/tp/cap5buddy/todolist/TodoList.java
  src/main/java/tp/cap5buddy/todolist/Type.java
Labels: priority.High, type.Task

#269 Delete contacts and grade components
  src/main/java/tp/cap5buddy/contacts/Contact.java
  src/main/java/tp/cap5buddy/contacts/ContactList.java
  src/main/java/tp/cap5buddy/contacts/Email.java
  src/main/java/tp/cap5buddy/contacts/Name.java
  src/main/java/tp/cap5buddy/contacts/exceptions/ContactNotFoundException.java
  src/main/java/tp/cap5buddy/contacts/exceptions/DuplicateContactException.java
  src/main/java/tp/cap5buddy/grades/FinalGrade.java
  src/main/java/tp/cap5buddy/grades/Grade.java
  src/main/java/tp/cap5buddy/grades/GradeList.java
  src/main/java/tp/cap5buddy/grades/GradeTracker.java
  src/main/java/tp/cap5buddy/modules/Module.java
  src/main/java/tp/cap5buddy/storage/JsonAdaptedGrade.java
  src/main/java/tp/cap5buddy/storage/JsonAdaptedModule.java
Labels: priority.High, type.Task

#251 Implement delete contact command for ContactList
  src/main/java/seedu/address/logic/commands/DeleteContactCommand.java
  src/main/java/seedu/address/logic/parser/DeleteContactParser.java
  src/main/java/seedu/address/logic/parser/ModuleListParser.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.High, type.Task, type.code

#271 Safe delete Storage and Module package
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/tp/cap5buddy/modules/Module.java
  src/main/java/tp/cap5buddy/modules/ModuleList.java
  src/main/java/tp/cap5buddy/storage/JsonAdaptedModule.java
  src/main/java/tp/cap5buddy/storage/JsonModuleListStorage.java
  src/main/java/tp/cap5buddy/storage/JsonSerializableModuleList.java
  src/main/java/tp/cap5buddy/storage/ModuleListStorage.java
  src/main/java/tp/cap5buddy/storage/Storage.java
  src/main/java/tp/cap5buddy/storage/StorageManager.java
  src/main/java/tp/cap5buddy/todolist/exception/DuplicateTaskException.java
  src/main/java/tp/cap5buddy/todolist/exception/TaskNotFoundException.java
Labels: priority.High

#273 Delete util and commons from former package
  src/main/java/tp/cap5buddy/commons/Config.java
  src/main/java/tp/cap5buddy/commons/LogsCenter.java
  src/main/java/tp/cap5buddy/util/AppUtil.java
  src/main/java/tp/cap5buddy/util/CollectionUtil.java
  src/main/java/tp/cap5buddy/util/ConfigUtil.java
  src/main/java/tp/cap5buddy/util/FileUtil.java
  src/main/java/tp/cap5buddy/util/JsonUtil.java
  src/main/java/tp/cap5buddy/util/StringUtil.java
Labels: type.Task, type.code

#243 Add TodoList to Model and ModelManager
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TodoList.java
  src/main/java/seedu/address/model/task/UniqueTodoList.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java
Labels: priority.High, type.Task, type.code

#277 Add Parser for Todo, and its respective sub-parsers and commands
  src/main/java/seedu/address/logic/commands/todolistcommands/AddTodoCommand.java
  src/main/java/seedu/address/logic/commands/todolistcommands/DeleteTodoCommand.java
  src/main/java/seedu/address/logic/commands/todolistcommands/EditTodoCommand.java
  src/main/java/seedu/address/logic/commands/todolistcommands/FindTodoCommand.java
  src/main/java/seedu/address/logic/commands/todolistcommands/HelpTodoCommand.java
  src/main/java/seedu/address/logic/commands/todolistcommands/ListTodoCommand.java
  src/main/java/seedu/address/logic/commands/todolistcommands/ViewTodoCommand.java
  src/main/java/seedu/address/logic/parser/TodoListParser.java
  src/main/java/seedu/address/logic/parser/todolistparsers/AddTodoParser.java
  src/main/java/seedu/address/logic/parser/todolistparsers/DeleteTodoParser.java
  src/main/java/seedu/address/logic/parser/todolistparsers/EditTodoParser.java
  src/main/java/seedu/address/logic/parser/todolistparsers/FindTodoParser.java
  src/main/java/seedu/address/logic/parser/todolistparsers/ViewTodoParser.java
Labels: priority.High, type.Task, type.code

#275 Enable assertions in build.gradle
  build.gradle
Labels: priority.High

#285 Developer's guide update: Added Explanation for Overall UML
  docs/DeveloperGuide.md
  docs/images/OverViewClassDiagram1.png
  docs/images/overallUML.png
Labels: priority.High, type.Task, type.documentation

#290 Add headers for features
  docs/DeveloperGuide.md
  docs/images/overallUML.png
Labels: priority.High, type.Task, type.documentation

#288 Add colour version of the Overall UML
  docs/images/overallUML.png
Labels: priority.High, type.Task, type.documentation

#283 Refactor Contact related Command and Parser classes
  src/main/java/seedu/address/logic/commands/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/DeleteContactCommand.java
  src/main/java/seedu/address/logic/commands/EditContactCommand.java
  src/main/java/seedu/address/logic/commands/contactlistcommands/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/contactlistcommands/DeleteContactCommand.java
  src/main/java/seedu/address/logic/commands/contactlistcommands/EditContactCommand.java
  src/main/java/seedu/address/logic/commands/contactlistcommands/EditContactDescriptor.java
  src/main/java/seedu/address/logic/parser/AddContactParser.java
  src/main/java/seedu/address/logic/parser/DeleteContactParser.java
  src/main/java/seedu/address/logic/parser/EditContactParser.java
  src/main/java/seedu/address/logic/parser/ModuleListParser.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/AddContactParser.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/ContactListParser.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/DeleteContactParser.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/EditContactParser.java
Labels: priority.High, type.Task

#279 Implement Add Grade Command
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/AddGradeCommand.java
  src/main/java/seedu/address/logic/parser/AddGradeParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ModuleListParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/grade/Grade.java
  src/main/java/seedu/address/model/module/grade/GradeTracker.java
  src/main/java/seedu/address/storage/JsonAdaptedGradeTracker.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
Labels: priority.High, type.code

#281 Add Event class and Supporting classes
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventName.java
  src/main/java/seedu/address/model/event/EventTime.java
  src/main/java/seedu/address/model/event/exceptions/EventDuplicateException.java
  src/main/java/seedu/address/model/event/exceptions/EventNotFoundException.java
  src/main/java/seedu/address/model/event/exceptions/EventOverlapException.java
Labels: priority.High, type.Task, type.code

#260 Implement tagging system for module tracker
  src/main/java/seedu/address/logic/commands/EditModuleCommand.java
  src/main/java/seedu/address/logic/parser/AddModuleParser.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/EditModuleParser.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
Labels: priority.High, type.Task, type.code

#301 Implement modular credits for each module
  src/main/java/seedu/address/logic/commands/EditModuleCommand.java
  src/main/java/seedu/address/logic/parser/AddModuleParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditModuleParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/module/ModularCredits.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
  src/main/java/seedu/address/ui/ModuleCard.java
  src/main/resources/view/ModuleListCard.fxml
  src/test/java/seedu/address/testutil/ModuleBuilder.java
Labels: priority.High, type.Task, type.code

#258 Implement ContactList storage
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/ContactListStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedContact.java
  src/main/java/seedu/address/storage/JsonContactListStorage.java
  src/main/java/seedu/address/storage/JsonSerializableContactList.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.High, type.Task, type.code

#305 V1.3 packaging module stuff
  src/main/java/seedu/address/logic/commands/modulelistcommands/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/AddZoomLinkCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/EditModuleCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/ViewModuleCommand.java
  src/main/java/seedu/address/logic/parser/ModuleListParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/AddModuleParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/AddZoomLinkParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/DeleteModuleParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/EditModuleParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/ViewModuleParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteModuleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddModuleParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteModuleParserTest.java
  src/test/java/seedu/address/logic/parser/EditModuleParserTest.java
  src/test/java/seedu/address/logic/parser/ModuleListParserTest.java
  src/test/java/seedu/address/testutil/EditModuleDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High

#297 TodoList : Add hasSame() method for Date, Priority, and Tag in Task class
  src/main/java/seedu/address/model/task/Task.java
Labels: priority.High, type.Task, type.code

#314 Add basic skeleton for Scheduler Logic
  src/main/java/seedu/address/logic/commands/schedulercommands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/schedulercommands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/schedulercommands/EditEventCommand.java
  src/main/java/seedu/address/logic/commands/schedulercommands/FindEventCommand.java
  src/main/java/seedu/address/logic/commands/schedulercommands/ViewEventCommand.java
  src/main/java/seedu/address/logic/parser/SchedulerParser.java
  src/main/java/seedu/address/logic/parser/schedulerparsers/AddEventParser.java
  src/main/java/seedu/address/logic/parser/schedulerparsers/DeleteEventParser.java
  src/main/java/seedu/address/logic/parser/schedulerparsers/EditEventParser.java
  src/main/java/seedu/address/logic/parser/schedulerparsers/FindEventParser.java
  src/main/java/seedu/address/logic/parser/schedulerparsers/ViewEventParser.java
Labels: priority.High, type.code

#326 DG : Update storage component
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
Labels: priority.High, type.Task, type.documentation

#299 Update DG CAPCalculator feature
  docs/DeveloperGuide.md
  docs/diagrams/CalculateCapSequenceDiagram.puml
  docs/images/CalculateCapSequenceDiagram.png
  src/main/java/seedu/address/model/module/Module.java
Labels: priority.High, type.Task, type.documentation

#327 Update Ui Component UML
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: priority.High, type.documentation

#322 V1.3 GUI Tabs pane
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
  src/main/java/seedu/address/ui/ContactCard.java
  src/main/java/seedu/address/ui/ContactListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ModuleCard.java
  src/main/java/seedu/address/ui/ModuleListPanel.java
  src/main/resources/view/ContactListCard.fxml
  src/main/resources/view/ContactListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModuleListPanel.fxml
  src/main/resources/view/TabPanestyle.css
Labels: priority.High, type.code

#343 Add ability to display contact list in GUI
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.High, type.code

#244 TodoList : Implement command to add a task to the list
  src/main/java/seedu/address/logic/commands/todolistcommands/AddTaskCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/todolistparsers/AddTaskParser.java
Labels: priority.High, type.Task, type.code

#307 TodoList : Implement command to delete a task
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/todolistcommands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/parser/todolistparsers/DeleteTaskParser.java
Labels: priority.High, type.Task, type.code

#339 TodoList : Implement command to label a task as completed
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/todolistcommands/CompleteTaskCommand.java
  src/main/java/seedu/address/logic/parser/TodoListParser.java
  src/main/java/seedu/address/logic/parser/todolistparsers/CompleteTaskParser.java
Labels: priority.High, type.Task, type.code

#311 TodoList : Implement command to list all tasks
  src/main/java/seedu/address/logic/commands/todolistcommands/ListTaskCommand.java
Labels: priority.High, type.Task, type.code

#341 Modify DG under Logic component
  docs/DeveloperGuide.md
  docs/diagrams/LogicClassDiagram.puml
  docs/images/Contact/AddContactCommandActivityDiagram.png
  docs/images/LogicClassDiagram.png
Labels: priority.High, type.documentation

#308 TodoList : Implement storage system
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/task/Priority.java
  src/main/java/seedu/address/model/task/Status.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/storage/JsonSerializableTodoList.java
  src/main/java/seedu/address/storage/JsonTodoListStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/TodoListStorage.java
Labels: priority.High, type.Task, type.code

#309 TodoList : Implement command to edit a task
  src/main/java/seedu/address/logic/commands/todolistcommands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/todolistcommands/EditTaskDescriptor.java
  src/main/java/seedu/address/logic/parser/todolistparsers/EditTaskParser.java
Labels: priority.High, type.Task, type.code

#320 TodoList : Implement command to sort tasks based on criterion
  src/main/java/seedu/address/logic/commands/todolistcommands/SortTaskCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/todolistparsers/SortTaskParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/task/Criterion.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java
Labels: priority.High, type.Task, type.code

#340 TodoList : Implement command to reset the status of a task
  src/main/java/seedu/address/logic/commands/todolistcommands/ResetTaskCommand.java
  src/main/java/seedu/address/logic/parser/TodoListParser.java
  src/main/java/seedu/address/logic/parser/todolistparsers/ResetTaskParser.java
Labels: priority.High, type.Task, type.code

#316 Add ParserManager and Interface FeatureParser
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/ParserManager.java
  src/main/java/seedu/address/logic/parser/FeatureParser.java
  src/main/java/seedu/address/logic/parser/ModuleListParser.java
  src/main/java/seedu/address/logic/parser/SchedulerParser.java
  src/main/java/seedu/address/logic/parser/TodoListParser.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/ContactListParser.java
Labels: priority.High, type.Task, type.code

#351 Update storage component description
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Task, type.documentation

#352 Update UG for Moduletracker
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Medium, type.Task, type.code

#323 DG : Update Model diagram and add TodoList Diagram
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/TodoListClassDiagram.puml
Labels: type.Task, type.documentation

#355 Update developer guide with contact list related implementations
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/contact/AddContactCommandActivityDiagram.puml
  docs/diagrams/contact/AddContactSequenceDiagram.puml
  docs/diagrams/contact/ContactClassDiagram.puml
  docs/images/Contact/AddContactCommandActivityDiagram.png
  docs/images/Contact/AddContactSequenceDiagram.png
  docs/images/Contact/ContactClassDiagram.png
  docs/team/joshuawong.md
  src/main/java/seedu/address/logic/commands/contactlistcommands/AddContactCommand.java
Labels: priority.High, type.documentation

#357 Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/model/AddAssignmentSequenceDiagram.puml
  docs/diagrams/model/ContactListDiagram.puml
  docs/diagrams/model/GradeTrackerDiagram.puml
  docs/diagrams/model/ModuleListDiagram.puml
  docs/images/AddAssignmentSequenceDiagram.png
  docs/images/GradeTrackerDiagram.png
  src/main/java/seedu/address/logic/commands/contactlistcommands/AddContactCommand.java
Labels: priority.High, type.documentation

#360 Add introduction for DG
  docs/DeveloperGuide.md
Labels: priority.High, type.Task, type.documentation

#362 Update UG command summary
  docs/UserGuide.md
Labels: priority.High, type.documentation

#359 Update DG for Scheduler
  docs/DeveloperGuide.md
  docs/diagrams/AddEventSequenceDiagram.puml
  docs/images/AddEventSequenceDiagram.png
Labels: priority.High, type.code

#363 Add command guide for add event
  docs/UserGuide.md
Labels: priority.High, type.documentation

#356 Update user guide with contact list features
  docs/UserGuide.md
Labels: priority.High, type.documentation

#331 DG : Update Model section and add TodoList section
  docs/DeveloperGuide.md
Labels: priority.High, type.Task, type.documentation

#365 Update UG Table of Contents
  docs/UserGuide.md
Labels: priority.High, type.documentation

#338 UG : Update with TodoList features
  docs/UserGuide.md
Labels: priority.High, type.Task, type.documentation

#367 Update UG commands summary and TOC
  docs/UserGuide.md
Labels: priority.High, type.documentation

#372 Module Tracker : Implement undo feature
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/gradetrackercommands/AddAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/gradetrackercommands/AddGradeCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/AddZoomLinkCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/EditModuleCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/ModuleListParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/UndoParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedModuleList.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java
Labels: priority.High, type.Task, type.code

#373 Module Tracker : Implement Redo feature
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/RedoCommand.java
  src/main/java/seedu/address/logic/parser/ModuleListParser.java
  src/main/java/seedu/address/logic/parser/UndoParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/RedoParser.java
  src/main/java/seedu/address/model/VersionedModuleList.java
Labels: priority.High, type.Task, type.code

#369 DG : Add diagram images for Model and TodoList
  docs/DeveloperGuide.md
  docs/images/ModelClassDiagram.png
  docs/images/TodoList/TodoListClassDiagram.png
Labels: priority.Low, type.documentation

#385 Fix bugs for PR #373
  src/main/java/seedu/address/logic/ParserManager.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/ModuleListParser.java
  src/main/java/seedu/address/logic/parser/UndoParser.java
  src/main/java/seedu/address/model/VersionedModuleList.java
Labels: priority.High, severity.High, type.Bug

#390 TodoList : Fix bugs
  src/main/java/seedu/address/logic/commands/todolistcommands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/todolistcommands/CompleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/todolistcommands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/todolistcommands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/todolistcommands/ResetTaskCommand.java
  src/main/java/seedu/address/logic/commands/todolistcommands/ViewTaskCommand.java
  src/main/java/seedu/address/model/task/Task.java
Labels: severity.High, type.Bug, type.code

#381 Implement List contact command
  src/main/java/seedu/address/logic/commands/contactlistcommands/ListContactCommand.java
  src/main/java/seedu/address/logic/commands/contactlistcommands/ViewContactCommand.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/ContactListParser.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/ViewContactParser.java
Labels: priority.High, type.Task, type.code

#383 Implement tagging feature for Contact
  src/main/java/seedu/address/logic/commands/contactlistcommands/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/contactlistcommands/EditContactCommand.java
  src/main/java/seedu/address/logic/commands/contactlistcommands/EditContactDescriptor.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/AddContactParser.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/EditContactParser.java
  src/main/java/seedu/address/model/contact/Contact.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedContact.java
  src/main/java/seedu/address/ui/ContactCard.java
  src/test/java/seedu/address/testutil/ContactBuilder.java
Labels: priority.High, type.Task, type.code

#306 TodoList : Enable Task class to store multiple tags
  src/main/java/seedu/address/logic/commands/todolistcommands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/todolistcommands/EditTaskDescriptor.java
  src/main/java/seedu/address/logic/parser/todolistparsers/AddTaskParser.java
  src/main/java/seedu/address/logic/parser/todolistparsers/EditTaskParser.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
Labels: priority.High, type.Task, type.code

#388 Implement Delete Assignment command
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/ParserManager.java
  src/main/java/seedu/address/logic/commands/gradetrackercommands/DeleteAssignmentCommand.java
  src/main/java/seedu/address/logic/parser/GradeTrackerParser.java
  src/main/java/seedu/address/logic/parser/ModuleListParser.java
  src/main/java/seedu/address/logic/parser/gradetrackerparsers/DeleteAssignmentParser.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/grade/Assignment.java
  src/main/java/seedu/address/model/module/grade/GradeTracker.java
  src/main/java/seedu/address/model/module/grade/ReadOnlyGradeTracker.java
  src/main/java/seedu/address/model/module/grade/UniqueAssignmentList.java
  src/main/java/seedu/address/model/module/grade/comparator/AssignmentNameComparator.java
  src/main/java/seedu/address/model/module/grade/exceptions/AssignmentNotFoundException.java
  src/main/java/seedu/address/model/module/grade/exceptions/DuplicateAssignmentException.java
  src/main/java/seedu/address/ui/ModuleCard.java
  src/main/resources/view/ModuleListCard.fxml
Labels: priority.High, type.code

#394 Fix todolist storage bugs
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
Labels: priority.Medium, type.Task, type.code

#398 GradeTracker : Implement grade point
  src/main/java/seedu/address/logic/commands/modulelistcommands/EditModuleCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/EditModuleParser.java
  src/main/java/seedu/address/model/module/grade/GradePoint.java
  src/main/java/seedu/address/model/module/grade/GradeTracker.java
  src/main/java/seedu/address/storage/JsonAdaptedGradeTracker.java
Labels: priority.High, type.Task, type.code

#410 Fix for edit module inconsistency
  src/main/java/seedu/address/logic/commands/modulelistcommands/EditModuleCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/EditModuleDescriptor.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/EditModuleParser.java
  src/test/java/seedu/address/testutil/EditModuleDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High, type.code

#412 MainApp : Add initialization of TodoList from storage component
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/todolistcommands/ResetTaskCommand.java
Labels: priority.High, type.Bug, type.code

#404 GUI : Integrate TodoList
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/TodoListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TodoListCard.fxml
  src/main/resources/view/TodoListPanel.fxml
Labels: priority.High, type.Task, type.code

#415 GUI : Fix a typo in TodListCard.fxml file
  src/main/resources/view/TodoListCard.fxml
Labels: priority.High, severity.High, type.Bug

#405 Tests: ModuleList parsers, ParserUtil, Tokenizer
  src/main/java/seedu/address/logic/commands/modulelistcommands/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/EditModuleCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/AddModuleParser.java
  src/main/java/seedu/address/model/module/ModularCredits.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/ModuleName.java
  src/main/java/seedu/address/model/module/grade/GradeTracker.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddModuleParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/DeleteModuleParserTest.java
  src/test/java/seedu/address/logic/parser/EditModuleParserTest.java
  src/test/java/seedu/address/logic/parser/ModuleListParserTest.java
  src/test/java/seedu/address/testutil/EditModuleDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ModuleBuilder.java
  src/test/java/seedu/address/testutil/ModuleUtil.java
Labels: priority.High, type.code

#400 CAPCalculator : Implement calculatecap command
  src/main/java/seedu/address/logic/ParserManager.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/CalculateCapCommand.java
  src/main/java/seedu/address/logic/parser/ModuleListParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/AddCompletedModuleParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/CalculateCapParser.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
Labels: priority.Medium, type.Task, type.code

#422 Implement Telegram as an optional field when adding a Contact
  src/main/java/seedu/address/logic/commands/FindContactCommand.java
  src/main/java/seedu/address/logic/commands/contactlistcommands/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/contactlistcommands/DeleteContactCommand.java
  src/main/java/seedu/address/logic/commands/contactlistcommands/EditContactCommand.java
  src/main/java/seedu/address/logic/commands/contactlistcommands/FindContactCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/FindContactParser.java
  src/main/java/seedu/address/logic/parser/ModuleListParser.java
  src/main/java/seedu/address/logic/parser/PrefixPosition.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/AddContactParser.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/DeleteContactParser.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/EditContactParser.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/FindContactParser.java
  src/main/java/seedu/address/model/contact/Contact.java
  src/main/java/seedu/address/model/contact/Telegram.java
  src/main/java/seedu/address/storage/JsonAdaptedContact.java
  src/main/java/seedu/address/ui/ContactCard.java
  src/test/java/seedu/address/testutil/ContactBuilder.java
Labels: priority.High, severity.Medium, type.code

#421 ModuleTracker : Implement map to store multiple ZoomLinks in a module
  src/main/java/seedu/address/logic/commands/modulelistcommands/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/AddZoomLinkCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/EditModuleCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/EditModuleDescriptor.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/AddModuleParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/EditModuleParser.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
  src/main/java/seedu/address/storage/JsonAdaptedZoomLink.java
  src/main/java/seedu/address/ui/ModuleCard.java
  src/main/resources/view/ModuleListCard.fxml
  src/test/java/seedu/address/logic/parser/AddModuleParserTest.java
  src/test/java/seedu/address/logic/parser/EditModuleParserTest.java
  src/test/java/seedu/address/logic/parser/ModuleListParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/ModuleListTest.java
  src/test/java/seedu/address/testutil/EditModuleDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ModuleBuilder.java
  src/test/java/seedu/address/testutil/ModuleUtil.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High, type.Task, type.code

#425 Modify FindContactCommand to allow finding contacts by tags
  src/main/java/seedu/address/logic/commands/contactlistcommands/FindContactCommand.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/FindContactParser.java
  src/main/java/seedu/address/model/contact/ContactContainsTagsPredicate.java
  src/main/java/seedu/address/model/contact/FindContactCriteria.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High, severity.Medium, type.code

#428 ModuleList: Modify AddZoomLinkCommand to allow users to label zoom links
  src/main/java/seedu/address/logic/ParserManager.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/AddZoomDescriptor.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/AddZoomLinkCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/EditModuleCommand.java
  src/main/java/seedu/address/logic/parser/ModuleListParser.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/AddZoomLinkParser.java
  src/main/java/seedu/address/model/ModuleList.java
  src/main/java/seedu/address/model/module/UniqueModuleList.java
  src/main/java/seedu/address/model/module/ZoomLink.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
Labels: priority.High, severity.High, type.code

#420 Undo/Redo : Extend undo/redo commands to ContactList and TodoList
  src/main/java/seedu/address/logic/commands/contactlistcommands/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/contactlistcommands/DeleteContactCommand.java
  src/main/java/seedu/address/logic/commands/contactlistcommands/EditContactCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/todolistcommands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/todolistcommands/CompleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/todolistcommands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/todolistcommands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/todolistcommands/ListTaskCommand.java
  src/main/java/seedu/address/logic/commands/todolistcommands/ResetTaskCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedContactList.java
  src/main/java/seedu/address/model/VersionedModuleList.java
  src/main/java/seedu/address/model/VersionedTodoList.java
  src/main/java/seedu/address/model/exceptions/VersionedListException.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java
Labels: priority.Medium, type.Task, type.code

#386 ContactList : Implement command to sort the list
  src/main/java/seedu/address/logic/commands/contactlistcommands/ListContactCommand.java
  src/main/java/seedu/address/logic/commands/contactlistcommands/SortContactCommand.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/ContactListParser.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/SortContactParser.java
  src/main/java/seedu/address/model/ContactList.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/contact/ContactComparatorByName.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java
Labels: priority.High, type.Task, type.code

#413 Implement Edit Assignment Command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/gradetrackercommands/AddAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/gradetrackercommands/AddGradeCommand.java
  src/main/java/seedu/address/logic/commands/gradetrackercommands/DeleteAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/gradetrackercommands/EditAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/gradetrackercommands/EditAssignmentDescriptor.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/gradetrackerparsers/AddAssignmentParser.java
  src/main/java/seedu/address/logic/parser/gradetrackerparsers/AddGradeParser.java
  src/main/java/seedu/address/logic/parser/gradetrackerparsers/EditAssignmentParser.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/grade/Assignment.java
  src/main/java/seedu/address/model/module/grade/AssignmentName.java
  src/main/java/seedu/address/model/module/grade/AssignmentPercentage.java
  src/main/java/seedu/address/model/module/grade/AssignmentResult.java
  src/main/java/seedu/address/model/module/grade/GradeTracker.java
  src/main/java/seedu/address/model/module/grade/comparator/AssignmentNameComparator.java
  src/main/java/seedu/address/storage/JsonAdaptedAssignment.java
  src/main/java/seedu/address/storage/JsonAdaptedGradeTracker.java
  src/main/java/seedu/address/ui/ModuleCard.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
Labels: priority.High, type.code

#431 ContactList : Fix bug related to list command
  src/main/java/seedu/address/logic/commands/contactlistcommands/ListContactCommand.java
Labels: severity.Medium, type.Bug

#435 Update user guide
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
Labels: priority.High, type.documentation

#438 TodoList : Fix NullPointer issue caused by tags being null
  src/main/java/seedu/address/model/task/Task.java
Labels: severity.High, type.Bug, type.code

#442 Fix typo
  src/main/java/seedu/address/model/task/exceptions/DuplicateTaskException.java
Labels: priority.Low, type.Bug

#402 ContactList : Implement command to mark or unmark contact as important
  src/main/java/seedu/address/logic/commands/contactlistcommands/EditContactCommand.java
  src/main/java/seedu/address/logic/commands/contactlistcommands/ImportantContactCommand.java
  src/main/java/seedu/address/logic/commands/contactlistcommands/ResetContactCommand.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/AddContactParser.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/ContactListParser.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/ImportantContactParser.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/ResetContactParser.java
  src/main/java/seedu/address/model/contact/Contact.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedContact.java
  src/main/java/seedu/address/ui/ContactCard.java
  src/main/resources/view/ContactListCard.fxml
  src/test/java/seedu/address/testutil/ContactBuilder.java
Labels: priority.High, type.Task, type.code

#419 Implement FindTaskCommand for TodoList
  docs/images/Contact/AddContactCommandActivityDiagram.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/contactlistcommands/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/contactlistcommands/DeleteContactCommand.java
  src/main/java/seedu/address/logic/commands/contactlistcommands/EditContactCommand.java
  src/main/java/seedu/address/logic/commands/contactlistcommands/EditContactDescriptor.java
  src/main/java/seedu/address/logic/commands/contactlistcommands/FindContactCommand.java
  src/main/java/seedu/address/logic/commands/contactlistcommands/ListContactCommand.java
  src/main/java/seedu/address/logic/commands/todolistcommands/FindTaskCommand.java
  src/main/java/seedu/address/logic/parser/ModuleListParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/AddContactParser.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/DeleteContactParser.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/FindContactParser.java
  src/main/java/seedu/address/logic/parser/todolistparsers/FindTaskParser.java
  src/main/java/seedu/address/model/contact/Contact.java
  src/main/java/seedu/address/model/contact/ContactName.java
  src/main/java/seedu/address/model/contact/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/contact/Telegram.java
  src/main/java/seedu/address/model/task/FindTaskCriteria.java
  src/main/java/seedu/address/model/task/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/task/TaskContainsTagsPredicate.java
  src/main/java/seedu/address/model/task/TaskMatchesDatePredicate.java
  src/main/java/seedu/address/model/task/TaskMatchesPriorityPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedContact.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/contact/NameTest.java
  src/test/java/seedu/address/testutil/ContactBuilder.java
Labels: priority.High, type.Task, type.code

#448 V1.3 scheduler
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/ParserManager.java
  src/main/java/seedu/address/logic/commands/schedulercommands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/schedulercommands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/schedulercommands/EditEventCommand.java
  src/main/java/seedu/address/logic/commands/schedulercommands/ViewEventCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/schedulerparsers/AddEventParser.java
  src/main/java/seedu/address/logic/parser/schedulerparsers/DeleteEventParser.java
  src/main/java/seedu/address/logic/parser/schedulerparsers/EditEventParser.java
  src/main/java/seedu/address/logic/parser/schedulerparsers/SchedulerParser.java
  src/main/java/seedu/address/logic/parser/schedulerparsers/ViewEventParser.java
  src/main/java/seedu/address/model/EventList.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ModuleList.java
  src/main/java/seedu/address/model/ReadOnlyEventList.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/event/EventName.java
  src/main/java/seedu/address/model/event/EventTime.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/main/java/seedu/address/storage/EventListStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/JsonEventListStorage.java
  src/main/java/seedu/address/storage/JsonSerializableEventList.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/EventListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/EventListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: priority.High, type.code

#454 Implement command to clear contact list
  src/main/java/seedu/address/logic/commands/contactlistcommands/ClearContactCommand.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/ContactListParser.java
Labels: priority.High, priority.Medium, type.code

#451 TodoList : Implement command to clear the list
  src/main/java/seedu/address/logic/commands/todolistcommands/ClearTaskCommand.java
Labels: priority.High, type.Task, type.code

#440 Tests: Update tests for module parsers
  src/main/java/seedu/address/logic/commands/modulelistcommands/EditModuleCommand.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/EditModuleDescriptor.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/EditModuleParser.java
  src/main/java/seedu/address/model/module/ModuleName.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddModuleParserTest.java
  src/test/java/seedu/address/logic/parser/EditModuleParserTest.java
  src/test/java/seedu/address/testutil/EditModuleDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ModuleBuilder.java
  src/test/java/seedu/address/testutil/TypicalModules.java
Labels: priority.High, type.code

#445 Modify EditContactCommand to allow editing of tags
  src/main/java/seedu/address/logic/commands/contactlistcommands/EditContactCommand.java
  src/main/java/seedu/address/logic/commands/contactlistcommands/EditContactDescriptor.java
  src/main/java/seedu/address/logic/parser/contactlistparsers/EditContactParser.java
Labels: severity.High, type.Bug

#427 TodoList : Enable list to be sorted and filtered at the same time
  src/main/java/seedu/address/logic/commands/todolistcommands/ListTaskCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TodoListParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TodoList.java
  src/main/java/seedu/address/model/task/Criterion.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/UniqueTodoList.java
Labels: priority.High, type.Task, type.code

#456 Fix Viewmodule Command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/modulelistcommands/ViewModuleCommand.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/ViewModuleParser.java
Labels: priority.High, type.code

#453 ModuleTracker : Implement command to clear the list
  src/main/java/seedu/address/logic/commands/modulelistcommands/ClearModuleCommand.java
  src/main/java/seedu/address/logic/parser/GradeTrackerParser.java
  src/main/java/seedu/address/logic/parser/ModuleListParser.java
  src/main/java/seedu/address/logic/parser/schedulerparsers/SchedulerParser.java
  src/test/java/seedu/address/logic/parser/ModuleListParserTest.java
Labels: priority.High, type.Task, type.code

#447 Update UG for CAPCalculator commands
  docs/UserGuide.md
Labels: priority.Medium, type.Task, type.documentation

#459 Update index.md
  docs/images/Ui.png
Labels: type.documentation

#462 Update UG for module related features
  docs/UserGuide.md
Labels: priority.High, type.documentation

#467 GUI: Add display for module list tags
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/ui/ModuleCard.java
Labels: priority.Medium, type.Task, type.code

#457 V1.3 display left bar
  src/main/java/seedu/address/ui/DetailDisplay.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DetailsDisplay.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModuleListCard.fxml
Labels: priority.High, type.Task

#474 UG : Update TodoList and ContactList features content
  docs/UserGuide.md
Labels: priority.High, type.Task, type.documentation

#469 GUI: Update ContactCard
  src/main/java/seedu/address/ui/ContactCard.java
Labels: priority.High, type.Task, type.code

#476 Update UG to include Scheduler commands
  docs/UserGuide.md
Labels: priority.High, type.documentation

#473 TodoList : Fix cleartask command not detected bug
  src/main/java/seedu/address/logic/parser/TodoListParser.java
Labels: severity.Medium, type.Bug, type.code

#481 UG : Update UG for module list archive features
  docs/UserGuide.md
Labels: priority.High, type.Task, type.documentation

#482 Update user guide
  docs/UserGuide.md
  docs/images/StartingApp.png
  docs/index.md
Labels: type.documentation

#484 Add checks for index put of bound and invalid date
  src/main/java/seedu/address/logic/commands/schedulercommands/EditEventCommand.java
  src/main/java/seedu/address/logic/commands/schedulercommands/ViewEventCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/schedulerparsers/AddEventParser.java
Labels: priority.High, severity.High, type.Bug, type.code

#463 Update UG for Add completed module feature
  docs/UserGuide.md
Labels: priority.Medium, type.Task, type.documentation

#486 BugFix
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: priority.High, severity.High, type.Bug, type.code

#488 Fix typo in Addevent
  docs/UserGuide.md
Labels: priority.High, type.documentation

#490 Update user guide
  docs/UserGuide.md
Labels: type.documentation

#538 Bug : Fix "listtask" and "listcontact" commands
  src/main/java/seedu/address/logic/ParserManager.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/ListModuleCommand.java
  src/main/java/seedu/address/logic/parser/ModuleListParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/ModuleListParserTest.java
Labels: priority.High, severity.High, type.Bug, type.code

#541 Bug: Fix blank module lesson argument when adding a zoom link to a module and missing whitespaces in message constraints
  src/main/java/seedu/address/logic/commands/modulelistcommands/AddZoomDescriptor.java
  src/main/java/seedu/address/logic/commands/modulelistcommands/AddZoomLinkCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/AddZoomLinkParser.java
  src/main/java/seedu/address/model/contact/ContactComparatorByName.java
  src/main/java/seedu/address/model/contact/ContactName.java
  src/main/java/seedu/address/model/contact/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/ModuleLesson.java
  src/main/java/seedu/address/model/module/ZoomLink.java
  src/main/java/seedu/address/storage/JsonAdaptedContact.java
  src/main/java/seedu/address/ui/ContactCard.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.Medium, severity.Medium, type.code

#546 ModuleTracker : Refactor ZoomLink-related codes to use the new ModuleLesson class
  src/main/java/seedu/address/logic/commands/modulelistcommands/EditModuleCommand.java
  src/main/java/seedu/address/logic/parser/modulelistparsers/EditModuleParser.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
  src/main/java/seedu/address/storage/JsonAdaptedZoomLink.java
  src/test/java/seedu/address/testutil/ModuleBuilder.java
  src/test/java/seedu/address/testutil/TypicalModules.java
Labels: priority.High, type.Task, type.code

#551 ModuleLesson class: Add hashCode() method to avoid duplicate lessons and enable deleting a zoom link
  src/main/java/seedu/address/model/module/ModuleLesson.java
Labels: severity.High, type.Bug, type.code
